### PR TITLE
Fix #1540:  Merge document sides in evaluation call

### LINKED ISSUE #1540: Send one document as one document in evaluation service
### Task specification

In the evaluation service, we should send the document with both sides. Not each side as a separate document.

Marge the common attributes (they should be the same, or the crosscheck should fail anyway)

### PR DESCRIPTION
**Pull request by michal-rozehnal-w**

### CODE REVIEW

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationDocumentCheckResultBuilder.java [hunk 1]
```diff
@@ -0,0 +1,250 @@
...
+            final var document = EvaluateClientRequest.Document.builder()
+                    .type(documentVerification.getType())
+                    .status(EvaluateClientRequest.Status.SUCCESS)
+                    .images(new ArrayList<>())
+                    .build();
+
+            documents.add(document);
+        }
+
+        return new EvaluateClientRequest.DocumentCheckResult(documents, null);
```
[the remark this answers is not in the document]
Comment (michal-rozehnal-w) [reply enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationDocumentCheckResultBuilder.java]: Good catch, fixed and added test for it

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationDocumentCheckResultFactory.java [hunk 2]
```diff
@@ -0,0 +1,250 @@
...
+    private static DocumentResultEntity selectLatestDocumentResult(final DocumentVerificationEntity documentVerificationEntity) {
+        return documentVerificationEntity.getResults().stream()
+                .max(Comparator.comparing(DocumentResultEntity::getTimestampCreated))
+                .orElseThrow(() -> new IllegalStateException("Missing document result for documentVerificationId: %s".formatted(documentVerificationEntity.getId())));
+    }
+
+    private DocumentExtractedDataValue parseExtractedData(final DocumentResultEntity documentResult) {
+        try {
+            return OBJECT_MAPPER.readValue(documentResult.getExtractedData(), DocumentExtractedDataValue.class);
+        } catch (JsonProcessingException e) {
```
[the remark this answers is not in the document]
Comment (michal-rozehnal-w) [reply enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationDocumentCheckResultFactory.java:215]: Right, fixed and added test for it

File: enrollment-server-onboarding/src/test/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationDocumentCheckResultBuilderTest.java [hunk 3]
```diff
@@ -0,0 +1,418 @@
...
+                ))
+                .person(person)
+                .build();
+    }
+
+    private static EvaluateClientRequest.DocumentData buildExprectedDocumentData() {
+        return EvaluateClientRequest.DocumentData.builder()
+                .givenNames("John")
+                .surname("Doe")
+                .dateOfBirth(LocalDate.of(1999, 2, 15))
```
[the remark this answers is not in the document]
Comment (michal-rozehnal-w) [reply enrollment-server-onboarding/src/test/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationDocumentCheckResultBuilderTest.java]: Fixed

File: enrollment-server-onboarding/src/test/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationDocumentCheckResultBuilderTest.java [hunk 4]
```diff
@@ -0,0 +1,418 @@
...
+        // then
+        final var expectedData = EvaluateClientRequest.DocumentData.builder().build();
+        final var expectedPerson = EvaluateClientRequest.Person.builder().build();
+
+        final var expected = buildExpectedResult(expectedData, buildExpectedImages(), expectedPerson, 10, VERIFICATION_RESULT, null);
+        assertEquals(expected, result);
+    }
+
+    @Test
+    void testBuild_verificationResulIsNull() {
```
[the remark this answers is not in the document]
Comment (michal-rozehnal-w) [reply enrollment-server-onboarding/src/test/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationDocumentCheckResultBuilderTest.java]: Fixed

File: enrollment-server-onboarding/src/test/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationServiceTest.java [hunk 5]
```diff
@@ -69,7 +68,7 @@ class ClientEvaluationServiceTest {
     private CommonOnboardingService onboardingService;
 
     @Mock
-    private ProcessedDocumentDataRepository processedDocumentDataRepository;
+    private ClientEvaluationDocumentCheckResultBuilder clientEvaluationDocumentCheckResultBuilder;
```
[the remark this answers is not in the document]
Comment (michal-rozehnal-w) [reply enrollment-server-onboarding/src/test/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationServiceTest.java:72]: Fixed

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationDocumentCheckResultBuilder.java [hunk 6]
```diff
@@ -0,0 +1,250 @@
...
+        final var extractedData = documentsResult.stream()
+                .map(this::parseExtractedData)
+                .filter(Objects::nonNull)
+                .toList();
+
+        final var documentData = buildDocumentData(extractedData);
+
+        final var country = extractedData.stream()
+                .findFirst()
+                .map(DocumentExtractedDataValue::country)
```
[the remark this answers is not in the document]
Comment (michal-rozehnal-w) [reply enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationDocumentCheckResultBuilder.java]: Good idea, fixed

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationDocumentCheckResultBuilder.java [hunk 7]
```diff
@@ -0,0 +1,250 @@
...
+                .findFirst()
+                .map(DocumentVerificationEntity::getPhotoId)
+                .map(it -> processedDocumentByPhotoId.getOrDefault(it, null))
+                .orElse(null);
+
+        final var images = buildImages(processedDocument);
+
+        final var documentResult = documentsResult.stream()
+                .findFirst()
+                .map(DocumentResultEntity::getVerificationResult)
```
[the remark this answers is not in the document]
Comment (michal-rozehnal-w) [reply enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationDocumentCheckResultBuilder.java]: Fixed

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationService.java [hunk 8]
```diff
@@ -168,110 +163,6 @@ private EvaluateClientResponse callEvaluateClient(final EvaluateClientRequest re
         }
     }
 
-    private EvaluateClientRequest.DocumentCheckResult buildDocumentCheckResultWithExtractedData(
```
Comment (michal-rozehnal-w) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationService.java:171]: I moved it to separate component, because it is quite lot of code and little bit hiding the logic of the service

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationDocumentCheckResultBuilder.java [hunk 9]
```diff
@@ -0,0 +1,266 @@
...
+ * Builder for {@link EvaluateClientRequest.DocumentCheckResult}.
+ *
+ * @author Michal Rozehnal, michal.rozehnal@wultra.com
+ */
+@Component
+@AllArgsConstructor
+@Slf4j
+public class ClientEvaluationDocumentCheckResultBuilder {
+
+    private static final ObjectMapper OBJECT_MAPPER = JsonMapper.builder()
```
Comment (banterCZ) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationDocumentCheckResultBuilder.java]: Do we need a custom one, or may we inject an existing bean?

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationDocumentCheckResultBuilder.java [hunk 10]
```diff
@@ -0,0 +1,266 @@
...
+
+/**
+ * Builder for {@link EvaluateClientRequest.DocumentCheckResult}.
+ *
+ * @author Michal Rozehnal, michal.rozehnal@wultra.com
+ */
+@Component
+@AllArgsConstructor
+@Slf4j
+public class ClientEvaluationDocumentCheckResultBuilder {
```
Comment (banterCZ) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationDocumentCheckResultBuilder.java]: 🤔 When I see Builder, I expect the builder pattern, which this is not. What about `Factory` or any other ideas?

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationDocumentCheckResultFactory.java [hunk 11]
```diff
@@ -0,0 +1,266 @@
...
+        LocalDate dateOfBirth = null;
+
+        for (final var document : documents) {
+            final var documentData = document.data();
+            if (documentData == null) {
+                return null;
+            }
+
+            if (surname == null) {
+                surname = documentData.surname();
```
Comment (banterCZ) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationDocumentCheckResultFactory.java:104]: 🤔 What if, just theoretically, both sides have `surname`?

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationService.java (hunk 8 above)
Comment (banterCZ) [reply enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationService.java:171]: Very well!

File: enrollment-server-onboarding/src/test/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationDocumentCheckResultBuilderTest.java [hunk 12]
```diff
@@ -0,0 +1,457 @@
...
+
+/**
+ * Unit tests for {@link ClientEvaluationDocumentCheckResultBuilder}.
+ *
+ * @author Michal Rozehnal, michal.rozehnal@wultra.com
+ */
+@ExtendWith(MockitoExtension.class)
+class ClientEvaluationDocumentCheckResultBuilderTest {
+
+    private static final String NATIONALITY = "\"Czech\"";
```
Comment (banterCZ) [inline enrollment-server-onboarding/src/test/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationDocumentCheckResultBuilderTest.java]: Nitpick, I prefer text blocks to avoid escaping.

**Review by banterCZ — APPROVED** [review]
Looks good. I just suggest to reconsider naming.

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationDocumentCheckResultBuilder.java (hunk 10 above)
Comment (michal-rozehnal-w) [reply enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationDocumentCheckResultBuilder.java]: I was thinking about `mapper` or `converter`, but neither of them is appropriate, in my opinion, since there is more logic than simple mapping. I used `factory` and renamed the method from `build` to `create`.

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationDocumentCheckResultBuilder.java (hunk 9 above)
Comment (michal-rozehnal-w) [reply enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationDocumentCheckResultBuilder.java]: I tested it with one of our BE test and injected one is sufficient

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationDocumentCheckResultFactory.java (hunk 11 above)
Comment (michal-rozehnal-w) [reply enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationDocumentCheckResultFactory.java:104]: Very good question. Theoretically, it should never happen, but on the other hand, there could be nuances such as `Novák` on one document and `Novak` on the second one.
In my opinion, the find-first approach should be fine because there is still a list of `documents` with all the extracted data per document type, and no information is lost.

File: enrollment-server-onboarding/src/test/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationDocumentCheckResultBuilderTest.java (hunk 12 above)
Comment (michal-rozehnal-w) [reply enrollment-server-onboarding/src/test/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationDocumentCheckResultBuilderTest.java]: Fixed
