### PR TITLE
Fix #776: Improve audit of failed document uploads

### LINKED ISSUE #776: Improve audit of failed document uploads
Only successful document upload is audited.

### PR DESCRIPTION
**Pull request by banterCZ**

### CODE REVIEW

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/document/DocumentProcessingService.java [hunk 1]
```diff
@@ -410,14 +410,14 @@ private void processDocsSubmitResults(OwnerId ownerId, DocumentVerificationEntit
             docVerification.setErrorOrigin(ErrorOrigin.DOCUMENT_VERIFICATION);
             logger.info("Document verification ID: {}, failed: {}, {}",
                     docVerification.getId(), docSubmitResult.getErrorDetail(), ownerId);
-            auditService.audit(docVerification, "Document verification failed for user: {}", ownerId.getUserId());
+            auditService.audit(docVerification, "Document verification failed for user: {}, detail: {}", ownerId.getUserId(), docSubmitResult.getErrorDetail());
```
Comment (banterCZ) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/document/DocumentProcessingService.java:413]: Error detail is filled https://github.com/wultra/enrollment-server/pull/802/files#diff-26aa493e19b315afe12bf5109a4a6917933ba3f3e2539be648565116bdb18374R259 in case of `DocumentVerificationException` or `RemoteCommunicationException`.

**Review by romanstrobl — APPROVED** [review]
Looks OK.
