### PR TITLE
Fix #1646: Fix incorrect audit type

### LINKED ISSUE #1646: auditDocumentVerificationProvider has an incorrect audit type
### Affected product(s) and version(s)

_No response_

### Environment

_No response_

### Steps to reproduce, current result, expected result

the method `auditDocumentVerificationProvider` has two signatures.
One log audit type DOCUMENT_VERIFICATION_PROVIDER (correct)
One log audit type ONBOARDING_PROVIDER (incorrect)

Expectation the auditing of document verification provider is under the same type. 
We can have special audit type for certain action but we shall not put the audit type to more generic one.

### Log output

_No response_

### PR DESCRIPTION
**Pull request by michal-rozehnal-w**

### CODE REVIEW

File: enrollment-server-onboarding-common/src/test/java/com/wultra/app/onboardingserver/common/service/AuditServiceTest.java [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+        assertAuditDetail(auditDetailCaptor.getValue(), DOCUMENT_VERIFICATION_PROVIDER_CODE, expectedParams);
+    }
+
+    private static void assertAuditDetail(final AuditDetail auditDetail, final String expectedType, final Map<String, Object> expectedParams) {
+        assertEquals(expectedType, auditDetail.getType());
+        assertEquals(expectedParams, auditDetail.getParam());
+    }
+}
+
+
```
[the remark this answers is not in the document]
Comment (michal-rozehnal-w) [reply enrollment-server-onboarding-common/src/test/java/com/wultra/app/onboardingserver/common/service/AuditServiceTest.java]: Fixed

File: enrollment-server-onboarding-common/src/test/java/com/wultra/app/onboardingserver/common/service/AuditServiceTest.java [hunk 2]
```diff
@@ -0,0 +1,94 @@
...
+        // then
+        final Map<String, Object> expectedParams = Map.of(
+                ACTIVATION_ID_PARAM, ACTIVATION_ID,
+                USER_ID_PARAM, USER_ID,
+                DOCUMENT_RESPONSE_JSON_PARAM, documentResponseJson
+        );
+
+        verify(audit).info(eq(message), auditDetailCaptor.capture(), eq(USER_ID));
+
+        assertAuditDetail(auditDetailCaptor.getValue(), DOCUMENT_VERIFICATION_PROVIDER_CODE, expectedParams);
```
Comment (banterCZ) [inline enrollment-server-onboarding-common/src/test/java/com/wultra/app/onboardingserver/common/service/AuditServiceTest.java]: Nitpick: Extracting these two asserts into a method seems a little bit excessive to me.

**Review by banterCZ — APPROVED** [review]

File: enrollment-server-onboarding-common/src/test/java/com/wultra/app/onboardingserver/common/service/AuditServiceTest.java (hunk 2 above)
Comment (michal-rozehnal-w) [reply enrollment-server-onboarding-common/src/test/java/com/wultra/app/onboardingserver/common/service/AuditServiceTest.java]: You are right, originally I was thinking about more tests, but for now there is only one, so having the separate method doesn't bring any value.

**Review by zcgandcomp — APPROVED** [review]
The type was corrected to the correct one.
