### PR TITLE
Error handling from adapter and related refactoring

### LINKED ISSUE #272: Add blacklisted ID info to response from client evaluation service
Information about blacklisted ID should be added into the REST API response from client evaluation service and such event should be processed on the backend (special `errorDetail` saved into DB, updated identity verification state).

The change has impact on the REST API of Digital Onboarding Adapter.

### LINKED ISSUE #384: Improve handling of error responses in User Lookup
In case User Lookup fails, we should process the reason why User Lookup failed. Ideally the reason why lookup failed should be logged and stored in the database in column `error_detail`.

### PR DESCRIPTION
**Pull request by romanstrobl**
The pull request contains following changes:
- Fix #272
- Fix #384
- Set timestampFinished for identity verification at the end of process 
- Model package cleanup for REST Onboarding Provider

The concrete part of error handling will be handled in downstream (mapping of error codes to error detail).

### CODE REVIEW

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/PresenceCheckService.java [hunk 1]
```diff
@@ -267,7 +267,7 @@ private void evaluatePresenceCheckResult(OwnerId ownerId,
             case ACCEPTED:
                 idVerification.setStatus(IdentityVerificationStatus.ACCEPTED);
                 idVerification.setTimestampLastUpdated(ownerId.getTimestamp());
-                idVerification.setTimestampFinished(ownerId.getTimestamp());
+                // The timestampFinished parameter is not set yet, there are may be other steps ahead
```
Comment (banterCZ) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/PresenceCheckService.java:270]: The verb _are_ appears to be unnecessary.

**Review by banterCZ — APPROVED** [review]
Looks good.
