### PR TITLE
Fix #913: Improve error handling in MobileTokenController

### LINKED ISSUE #913: Improve error handling in MobileTokenController
`MobileTokenController` error handling is too strict. E.g. `/operation/history` catches `PowerAuthClientException` and remaps it to `MobileTokenAuthException`. The result is `401 Unauthorized` without any detail. Actually, the detail is only in the enrollment-server log.
We should provide some hints. The mobile application must be able to handle it.

❗ For missing authorization, 401 **must** remain.

Consider other methods in this controller as well.

### PR DESCRIPTION
**Pull request by jnpsk**
Fix #913 
by resolving the error code in the exception.

### CODE REVIEW

File: enrollment-server/src/main/java/com/wultra/app/enrollmentserver/controller/api/MobileTokenController.java [hunk 1]
```diff
@@ -68,6 +71,13 @@
 @RequestMapping("api/auth/token/app")
 public class MobileTokenController {
 
+    public static final String APPLICATION_NOT_FOUND = "ERR0015";
```
Comment (banterCZ) [inline enrollment-server/src/main/java/com/wultra/app/enrollmentserver/controller/api/MobileTokenController.java:74]: May we stick with private constants?

File: enrollment-server/src/main/java/com/wultra/app/enrollmentserver/controller/api/MobileTokenController.java [hunk 2]
```diff
@@ -115,8 +125,24 @@ public ObjectResponse<OperationListResponse> operationList(@Parameter(hidden = t
...
+                }
+                case INVALID_REQUEST -> {
+                    logger.info("Request validation error: {}", e.getMessage());
+                    logger.debug("Request validation error.", e);
+                    throw new MobileTokenException(ErrorCode.INVALID_REQUEST, "Request validation error: %s".formatted(e.getMessage()));
+                }
+                default -> {
+                    logger.warn("Calling PowerAuth service failed: {}", e.getMessage());
+                    logger.debug("Calling PowerAuth service failed.", e);
+                    throw new InternalServiceException("Unable to call upstream service.");
```
Comment (banterCZ) [inline enrollment-server/src/main/java/com/wultra/app/enrollmentserver/controller/api/MobileTokenController.java:143]: 🤔 Is it really `InternalServiceException` or rather `RemoteCommunicationException`? Moreover, we provide details for  the `ERR0015` and `ERR0024` only, other error codes cause `InternalServiceException`, correct? But we map `RemoteCommunicationException` to 409 status code.

File: mtoken-model/src/main/java/com/wultra/security/powerauth/lib/mtoken/model/enumeration/ErrorCode.java [hunk 3]
```diff
@@ -42,6 +42,18 @@ public class ErrorCode {
      */
     public static final String INVALID_ACTIVATION           = "INVALID_ACTIVATION";
 
+    /**
+     * Error code for situation when an invalid application identifier is
+     * attempted for operation manipulation.
+     */
+    public static final String INVALID_APPLICATION          = "INVALID_APPLICATION";
```
Comment (banterCZ) [inline mtoken-model/src/main/java/com/wultra/security/powerauth/lib/mtoken/model/enumeration/ErrorCode.java:49]: I suppose that these error codes should be discussed with @kober32 and @Hopsaheysa

Comment (kober32) [reply mtoken-model/src/main/java/com/wultra/security/powerauth/lib/mtoken/model/enumeration/ErrorCode.java:49]: It would be nice to give us examples of when those 2 errors can happen so we can make a hint for the mobile devs what to show to the user.

**Review by romanstrobl — APPROVED** [review]
I have nothing to add, however I agree with @banterCZ comments, especially reusing the `RemoteCommunicationException` for consistency with other endpoints. It would be probably confusing to introduce a new exception class for the same purpose.

**Review by banterCZ — APPROVED** [review]
Ok from BE point of view. Let's wait for approval from mobile developers.

File: mtoken-model/src/main/java/com/wultra/security/powerauth/lib/mtoken/model/enumeration/ErrorCode.java (hunk 3 above)
Comment (jnpsk) [reply mtoken-model/src/main/java/com/wultra/security/powerauth/lib/mtoken/model/enumeration/ErrorCode.java:49]: This controller handles endpoints on the path `/api/auth/token/app`

**INVALID_APPLICATION** (status 400) happens if the application specified by `applicationId` in a request does not exist. Relevant to:
```
/operation/list
/operation/history
/operation/authorize
/operation/cancel
```

**INVALID_OPERATION** (status 400) may happen in any of the three cases:  
1. Operation specified by `operationId` in a request does not exist. Relevant to:
```
/operation/detail
/operation/detail/claim
/operation/authorize
/operation/cancel
```
2. Operation is not claimed to the user specified by `userId` in a request. Relevant to:
```
/operation/authorize
/operation/cancel 
```
3. Operation specified by `operationId` in a request is not in the `PENDING` state. Relevant to:
```
/operation/authorize
/operation/cancel 
```

**INVALID_REQUEST** (status 400) may happen in any of the six endpoints in case a required field of a request is missing.

**REMOTE_COMMUNICATION_ERROR** (status 409) may happen in any of the six endpoints in case an unexpected error caused by remote server occurs.

**Review by kober32 — APPROVED** [review]
OK
