### PR TITLE
Fix #1615: Set error when document verification fails

### LINKED ISSUE #1615: Microblink set error when document crosscheck fails
### Task specification

When document crosscheck fails then exception is thrown but error is not set to the documents. It causes issue that mobile doesn't know the validation fails because the information is not returned in document status endpoint response.
The crosscheck code: https://github.com/wultra/enrollment-server/blob/develop/enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java#L748
The main problem is that the FE isn’t aware of the error and ends up stuck in an infinite loop. On the other hand, we shouldn’t expose too many details about the validation error.

FE logs:
```
[WPN] - Status code: 200
[WPN] - Headers: 11 filtered out
[WPN] - Body: {"status":"OK","responseObject":{"config":{"otpResendPeriod":"PT30S","otpResendPeriodSeconds":30},"processId":"7583c0b3-09d6-475b-ba10-63afdb0f34bc","identityVerificationStatus":"IN_PROGRESS","identityVerificationPhase":"DOCUMENT_VERIFICATION_FINAL","processType":"onboarding_SVK"}}
[WDO] Verification status successfully retrieved.
```

BE logs:
```
"'@timestamp"	message	"trace.id"	"error.exception.message"
"Mar 17, 2026 @ 17:06:57.034"	"Changed state of 1 identity verifications"	70ba325c6ece7bd2068ca97edfcc4ca6	"(null)"
"Mar 17, 2026 @ 17:06:57.029"	"Unexpected targetState=OnboardingState.DOCUMENT_VERIFICATION_FINAL_ACCEPTED(phase=DOCUMENT_VERIFICATION_FINAL, status=ACCEPTED) when expectedState=OnboardingState.DOCUMENT_VERIFICATION_FINAL_IN_PROGRESS(phase=DOCUMENT_VERIFICATION_FINAL, status=IN_PROGRESS), IdentityVerificationEntity(id=42b140e0-ff15-477e-9de0-f7f13c1e25bb, activationId=2ad3a58c-c608-4fa9-bfb1-87afbe9f22e4, status=IN_PROGRESS, phase=DOCUMENT_VERIFICATION_FINAL)"	70ba325c6ece7bd2068ca97edfcc4ca6	"(null)"
"Mar 17, 2026 @ 17:06:57.029"	"State changed from OnboardingState.DOCUMENT_VERIFICATION_FINAL_IN_PROGRESS(phase=DOCUMENT_VERIFICATION_FINAL, status=IN_PROGRESS) to OnboardingState.DOCUMENT_VERIFICATION_FINAL_ACCEPTED(phase=DOCUMENT_VERIFICATION_FINAL, status=ACCEPTED)"	70ba325c6ece7bd2068ca97edfcc4ca6	"(null)"
"Mar 17, 2026 @ 17:06:57.027"	"Document verification failed"	70ba325c6ece7bd2068ca97edfcc4ca6	"Crosscheck failed for field lastName"
"Mar 17, 2026 @ 17:06:57.026"	"Document verification failed: Crosscheck failed for field lastName"	70ba325c6ece7bd2068ca97edfcc4ca6	"(null)"
"Mar 17, 2026 @ 17:06:57.026"	"action: verifyDocuments, state: failed, provider: microblink, error: Crosscheck failed for field lastName"	70ba325c6ece7bd2068ca97edfcc4ca6	"(null)"
"Mar 17, 2026 @ 17:06:57.015"	"action: verifyDocuments, state: initiated, provider: microblink, ownerId: OwnerId(activationId=2ad3a58c-c608-4fa9-bfb1-87afbe9f22e4, userId=mockuser_Kakskskjdjd), uploadIds: [3b7aef1a-9cec-4607-8814-09ef6933ffab, 0561b843-91e7-48e7-8186-a4df5b286da2, 138e8b3a-1667-4116-b746-272d8faad606], verificationId: 670c0ba9-7eaf-4022-99ed-a3be44bf32e5"	70ba325c6ece7bd2068ca97edfcc4ca6	"(null)"
"Mar 17, 2026 @ 17:06:57.014"	"Onboarding process will be locked using PESSIMISTIC_WRITE lock, 99160276-e8ff-4cba-a002-48552b3fec45"	70ba325c6ece7bd2068ca97edfcc4ca6	"(null)"
"Mar 17, 2026 @ 17:06:57.009"	"Changing state of machine for process ID: 99160276-e8ff-4cba-a002-48552b3fec45"	70ba325c6ece7bd2068ca97edfcc4ca6	"(null)"
```

### PR DESCRIPTION
**Pull request by michal-rozehnal-w**

### CODE REVIEW

File: enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java [hunk 1]
```diff
@@ -330,7 +339,10 @@ private DocumentVerificationResponseBundle sendApiRequest(
                     .map(HttpEntity::getBody)
                     .orElseThrow(() -> new DocumentVerificationException("Response body is empty"));
 
-            final var parsedResponse = parseMicroblinkResponse(body);
+            final var parsedResponse = Optional.of(body)
+                    .map(this::parseMicroblinkResponse)
+                    .orElseThrow(() -> new DocumentVerificationException("Failed to parse Microblink API response"));
+
```
[the remark this answers is not in the document]
Comment (michal-rozehnal-w) [reply enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java]: We log the root exception in the `parseMicroblinkResponse` method

File: enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java [hunk 2]
```diff
@@ -600,79 +613,141 @@ private DocumentsVerificationResult verifyDocuments(List<String> uploadIds, Stri
...
 
-                final var overallExtraction = microblinkResponse.extraction().overall();
-                final var crosscheckData = buildCrosscheckData(overallExtraction);
-                crosscheckDataByDocumentType.put(documentType, crosscheckData);
-            }
+    @SneakyThrows
+    private DocumentVerificationResultBundle verifyDocument(
+            final Map<String, DocumentVerificationEntity> documentsVerificationByUploadId,
+            final String uploadId
+    ) {
```
[the remark this answers is not in the document]
Comment (michal-rozehnal-w) [reply enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java:647]: I used the `@SneakyThrows` so it can be used in stream, it should not have any impact on logic

File: enrollment-server-onboarding-provider-microblink/src/test/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProviderTest.java [hunk 3]
```diff
@@ -570,253 +575,226 @@ void testSubmitDocuments_documentVerificationEntityWithoutSide_firstDocumentVeri
...
-    void testVerifyDocuments_missingAllVerificationData_exceptionIsThrown() {
+    void testVerifyDocuments_emptyDocumentVerifications_rejectResult() {
         // given
-        final var uploadIds = List.of(DOCUMENT_ID_CARD_FRONT_UPLOAD_ID, DOCUMENT_ID_CARD_BACK_UPLOAD_ID);
-        when(documentVerificationRepository.findAllByUploadIds(uploadIds)).thenReturn(List.of());
+        when(documentVerificationRepository.findAllByUploadIds(anyList())).thenReturn(List.of());
 
         // when
-        final var error = assertThrows(DocumentVerificationException.class, () -> provider.verifyDocuments(ownerId, uploadIds));
+        final var result = provider.verifyDocuments(ownerId, List.of(DOCUMENT_ID_CARD_FRONT_UPLOAD_ID));
```
[the remark this answers is not in the document]
Comment (michal-rozehnal-w) [reply enrollment-server-onboarding-provider-microblink/src/test/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProviderTest.java:581]: We recently had a [discussion](https://github.com/wultra/enrollment-server/pull/1643/changes#r2986116123) about having a relaxing stubbing session instead of strict one.

File: enrollment-server-onboarding-provider-microblink/src/test/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProviderTest.java [hunk 4]
```diff
@@ -570,253 +575,226 @@ void testSubmitDocuments_documentVerificationEntityWithoutSide_firstDocumentVeri
...
+    void testVerifyDocuments_missingDocumentResult_reject() {
         // given
         final var uploadIds = List.of(DOCUMENT_ID_CARD_FRONT_UPLOAD_ID);
 
-        final var documentVerifications = buildDocumentVerifications(List.of(verificationDocumentCardIdFront), Set.of());
-        when(documentVerificationRepository.findAllByUploadIds(uploadIds)).thenReturn(documentVerifications);
+        final var documentResult = new DocumentResultEntity();
+        documentResult.setVerificationResult(
+                buildMicroblinkResponseJson(CheckResult.PASS, Type.ID, "invalid_json", "[]", "[]", null)
+        );
```
[the remark this answers is not in the document]
Comment (michal-rozehnal-w) [reply enrollment-server-onboarding-provider-microblink/src/test/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProviderTest.java]: Fixed

File: enrollment-server-onboarding-provider-microblink/src/test/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProviderTest.java [hunk 5]
```diff
@@ -570,253 +575,226 @@ void testSubmitDocuments_documentVerificationEntityWithoutSide_firstDocumentVeri
...
 
         // when
-        final var error = assertThrows(DocumentVerificationException.class, () -> provider.verifyDocuments(ownerId, uploadIds));
+        final var result = provider.verifyDocuments(ownerId, List.of(DOCUMENT_ID_CARD_FRONT_UPLOAD_ID));
 
         // then
-        assertEquals("No document verification data found for uploadIds: [52ca4d10-06ac-442c-934c-9d085ab18934, bdfb45ce-a808-4b65-86a8-9f5f184c56f6]", error.getMessage());
+        assertEquals(DocumentVerificationStatus.FAILED, result.getStatus());
+        assertEquals("Microblink provider exception: DocumentVerificationException No document verification data found for uploadIds: [52ca4d10-06ac-442c-934c-9d085ab18934]", result.getErrorDetail());
     }
```
[the remark this answers is not in the document]
Comment (michal-rozehnal-w) [reply enrollment-server-onboarding-provider-microblink/src/test/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProviderTest.java:585]: Fixed

File: enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java [hunk 6]
```diff
@@ -228,24 +229,32 @@ public boolean shouldStoreSelfie() {
...
+        try {
             final var result = verifyDocuments(uploadIds, verificationId);
 
             logger.info("action: verifyDocuments, state: succeeded, provider: microblink, result: {}", result.getStatus());
             return result;
-        } catch (final DocumentVerificationException e) {
-            logger.info("action: verifyDocuments, state: failed, provider: microblink, error: {}", e.getMessage());
-            throw e;
+        } catch (final DocumentVerificationException | RuntimeException e) {
+            logger.info("action: verifyDocuments, state: failed, provider: microblink, error: {}", e.getMessage(), e);
```
[the remark this answers is not in the document]
Comment (michal-rozehnal-w) [reply enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java]: Added extra logging for the error

File: enrollment-server-onboarding-domain-model/src/main/java/com/wultra/app/enrollmentserver/model/integration/DocumentsVerificationResult.java [hunk 7]
```diff
@@ -28,6 +31,9 @@
  * @author Roman Strobl, roman.strobl@wultra.com
  */
 @Data
+@Builder
+@NoArgsConstructor
+@AllArgsConstructor
```
Comment (michal-rozehnal-w) [inline enrollment-server-onboarding-domain-model/src/main/java/com/wultra/app/enrollmentserver/model/integration/DocumentsVerificationResult.java:37]: Added `Builder` because otherwise there will a lot of null params in the Microblink provider. `AllArgs` and `NoArgs` constructors are for backward compatibility because I didn't want to touch other providers in this PR. We can refactor it in other issue - user `Builder` everywhere instead of `NoArgs` + setters

File: enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java [hunk 8]
```diff
@@ -224,24 +225,33 @@ public boolean shouldStoreSelfie() {
...
-        try {
-            final var verificationId = UUID.randomUUID().toString();
-
-            logger.info(
-                    "action: verifyDocuments, state: initiated, provider: microblink, ownerId: {}, uploadIds: {}, verificationId: {}",
-                    ownerId,
-                    uploadIds,
-                    verificationId
-            );
+    public DocumentsVerificationResult verifyDocuments(OwnerId ownerId, List<String> uploadIds) {
```
Comment (michal-rozehnal-w) [inline enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java:228]: This method no longer throws any exceptions. Instead, it uses the rejectReason and errorDetail fields, which helps with processing in upper layers. Throwing an exception caused the onboarding process to get stuck in `IN_PROGRESS`

**Comment by michal-rozehnal-w** [comment]
@marek-ch FYI, we can retest this fix once it is merged and deployed to DEV

Example of OLD responses, when documents crosscheck fails:

```
POST /api/identity/status
{
    "status": "OK",
    "responseObject": {
        "config": {
            "otpResendPeriod": "PT30S",
            "otpResendPeriodSeconds": 30
        },
        "processId": "073d890b-7e01-4b2f-b72c-b72d7f60d957",
        "identityVerificationStatus": "IN_PROGRESS",
        "identityVerificationPhase": "DOCUMENT_VERIFICATION_FINAL",
        "processType": "onboardingSimple",
        "consentRequired": false
    }
}

POST /api/identity/document/status
{
    "status": "OK",
    "responseObject": {
        "status": "IN_PROGRESS",
        "documents": [
            {
                "filename": "images/id_card_mock_back.png",
                "id": "e0200e88-f09f-4e82-ab20-3065f97109f8",
                "type": "ID_CARD",
                "side": "BACK",
                "status": "ACCEPTED"
            },
            {
                "filename": "images/id_card_mock_front.png",
                "id": "252562eb-ffed-4032-b349-6ba57243b057",
                "type": "ID_CARD",
                "side": "FRONT",
                "status": "ACCEPTED"
            },
            {
                "filename": "images/driving_license_mock_front.png",
                "id": "28370450-8a83-4307-bf98-617b203b978a",
                "type": "DRIVING_LICENSE",
                "side": "FRONT",
                "status": "ACCEPTED"
            }
        ]
    }
}
```

Example of NEW responses:

```
POST /api/identity/status
{
    "status": "OK",
    "responseObject": {
        "config": {
            "otpResendPeriod": "PT30S",
            "otpResendPeriodSeconds": 30
        },
        "processId": "55017232-942f-4a69-904b-758003c5720f",
        "identityVerificationStatus": "REJECTED",
        "identityVerificationPhase": "DOCUMENT_VERIFICATION_FINAL",
        "processType": "onboardingSimple",
        "rejectReason": "documentVerificationRejected",
        "consentRequired": false
    }
}

POST /api/identity/document/status
{
    "status": "OK",
    "responseObject": {
        "status": "REJECTED",
        "documents": [
            {
                "filename": "images/id_card_mock_front.png",
                "id": "c7524085-5707-410a-ac4b-60967b2752d3",
                "type": "ID_CARD",
                "side": "FRONT",
                "status": "REJECTED",
                "errors": [
                    "Error verifying the document."
                ]
            },
            {
                "filename": "images/id_card_mock_back.png",
                "id": "15764db4-0264-4c23-9703-68a04ba363a9",
                "type": "ID_CARD",
                "side": "BACK",
                "status": "REJECTED",
                "errors": [
                    "Error verifying the document."
                ]
            },
            {
                "filename": "images/driving_license_mock_front.png",
                "id": "5446b3b3-ac9a-4536-8c82-614798e5d7da",
                "type": "DRIVING_LICENSE",
                "side": "FRONT",
                "status": "REJECTED",
                "errors": [
                    "Error verifying the document."
                ]
            }
        ]
    }
}
```

File: enrollment-server-onboarding-domain-model/src/main/java/com/wultra/app/enrollmentserver/model/integration/DocumentsVerificationResult.java (hunk 7 above)
Comment (banterCZ) [reply enrollment-server-onboarding-domain-model/src/main/java/com/wultra/app/enrollmentserver/model/integration/DocumentsVerificationResult.java:37]: Ok, it could be done in a consecutive PR, but in general, I do not like the combination of builders and constructors. Please rather add a TODO.

File: enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (banterCZ) [reply enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java]: 🤔 Copilot is right, later, we may introduce the `TrySuccess` pattern as we have in Cloud-Signer.

File: enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java [hunk 9]
```diff
@@ -368,7 +381,8 @@ private DocumentVerificationResponseBundle parseMicroblinkResponse(final String
                     .map(matcher -> matcher.group(1))
                     .orElse(null);
 
-            throw new DocumentVerificationException("Failed to parse Microblink API response. Microblink traceId: %s".formatted(traceId), e);
+            logger.warn("Failed to parse Microblink API response, response body is not valid JSON. Microblink traceId: {}", traceId, e);
+            return null;
```
Comment (banterCZ) [inline enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java]: 🤔 What about returning `Optional#empty` instead of `null`?

File: enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java [hunk 10]
```diff
@@ -596,79 +610,141 @@ private DocumentsVerificationResult verifyDocuments(List<String> uploadIds, Stri
...
+                .map(DocumentVerificationResultBundle::result)
+                .toList();
 
-            final var documentType = documentVerification.getType();
-            final var documentResult = documentVerification.getResults()
-                    .stream()
-                    .findFirst()
-                    .orElseThrow(() -> new DocumentVerificationException("No document result data found for uploadId: " + documentVerification.getUploadId()));
+        final var rejectReasons = documentResults.stream()
+                .filter(it -> it.getRejectReason() != null)
```
Comment (banterCZ) [inline enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java]: Nitpick: Personally, I would add a specific method to the class.

File: enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java [hunk 11]
```diff
@@ -596,79 +610,141 @@ private DocumentsVerificationResult verifyDocuments(List<String> uploadIds, Stri
...
+                .map(it -> "uploadId=%s, rejectReason=%s".formatted(it.getUploadId(), it.getRejectReason()))
+                .collect(Collectors.toCollection(ArrayList::new));
 
-            final var microblinkResponseBundle = parseMicroblinkResponse(documentResult.getVerificationResult());
-            final var microblinkResponse = microblinkResponseBundle.getParsedResponseBody();
+        if (properties.isExtractedDataCheckEnabled() && rejectReasons.isEmpty()) {
+            final var crosscheckFailedFields = performDocumentsCrosscheck(documentVerificationResultBundles);
+            final var crosscheckPassed = crosscheckFailedFields.isEmpty();
+            logger.info("Document data crosscheck passed: {}, failedFields: {}, uploadIds: {}", crosscheckPassed, crosscheckFailedFields, uploadIds);
```
Comment (banterCZ) [inline enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java:628]: 🤔 Don't we want to keep `action` in the log message here?

File: enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java [hunk 12]
```diff
@@ -596,79 +610,141 @@ private DocumentsVerificationResult verifyDocuments(List<String> uploadIds, Stri
...
-            }
+        final var documentType = documentVerification.getType();
+        final var documentResult = documentVerification.getResults()
+                .stream()
+                .findFirst()
+                .orElse(null);
 
-            documentVerificationResults.add(documentVerificationResult);
+        if (documentResult == null) {
+            throw new DocumentVerificationException("Document result not found for uploadId=%s".formatted(uploadId));
```
Comment (banterCZ) [inline enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java]: Nitpick: If adding only one parameter at the end, isn't `formatted()` superfluous?

File: enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java [hunk 13]
```diff
@@ -596,79 +610,141 @@ private DocumentsVerificationResult verifyDocuments(List<String> uploadIds, Stri
...
+            documentVerificationResultBuilder.rejectReason("Rejected by provider " + rejectReasons);
+            documentVerificationResultBuilder.verificationResult(documentResult.getVerificationResult());
+            documentVerificationResultBuilder.extractedData(documentResult.getExtractedData());
+            documentVerificationResultBuilder.verificationScore(score);
+            return createDocumentVerificationResultBundle(documentVerificationResultBuilder, null);
         }
 
-        return result;
-    }
+        DocumentCrosscheckData crosscheckData = null;
```
Comment (banterCZ) [inline enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java]: May we make it _final_?

File: enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java [hunk 14]
```diff
@@ -736,55 +812,67 @@ private static DocumentCrosscheckData buildCrosscheckData(final List<DocumentVer
                 .build();
     }
 
-    private static LocalDate parseDate(final DocumentVerificationResponse.Result result) throws DocumentVerificationException {
-        final var year = Optional.ofNullable(result.year())
-                .orElseThrow(() -> new DocumentVerificationException("Year of field DateOfBirth was not extracted"));
+    private static LocalDate parseDate(final DocumentVerificationResponse.Result result) {
+        try {
+            return LocalDate.of(result.year(), result.month(), result.day());
+        } catch (final RuntimeException e) {
```
Comment (banterCZ) [inline enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java:816]: Please do not swallow exceptions.

File: enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java [hunk 15]
```diff
@@ -736,55 +812,67 @@ private static DocumentCrosscheckData buildCrosscheckData(final List<DocumentVer
...
 
-        if (extractedDocumentType != claimedDocumentType) {
-            throw new DocumentVerificationException(
-                    "Extracted document type %s does not match claimed type %s".formatted(
-                            extractedDocumentType,
-                            claimedDocumentType
-                    )
-            );
+        if (extractedDocumentType == DocumentType.UNKNOWN) {
+            logger.warn("Unsupported document type '{}' for document uploadId={}", uploadId, extractedType);
```
Comment (banterCZ) [inline enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java]: The log parameters are in the wrong order.

**Review by banterCZ — APPROVED** [review]
I added several ideas to consider.

File: enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java (hunk 10 above)
Comment (michal-rozehnal-w) [reply enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java]: I created the method

File: enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java (hunk 11 above)
Comment (michal-rozehnal-w) [reply enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java:628]: It is probably not necessary, there is corresponding structured logging in the `verifyDocuments` method

File: enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java (hunk 9 above)
Comment (michal-rozehnal-w) [reply enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java]: Good idea, applied

File: enrollment-server-onboarding-domain-model/src/main/java/com/wultra/app/enrollmentserver/model/integration/DocumentsVerificationResult.java (hunk 7 above)
Comment (michal-rozehnal-w) [reply enrollment-server-onboarding-domain-model/src/main/java/com/wultra/app/enrollmentserver/model/integration/DocumentsVerificationResult.java:37]: Right, added the TODO comments

File: enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java (hunk 12 above)
Comment (michal-rozehnal-w) [reply enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java]: Yes, I used `+` operator

File: enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java (hunk 14 above)
Comment (michal-rozehnal-w) [reply enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java:816]: Good catch, added

File: enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java (hunk 15 above)
Comment (michal-rozehnal-w) [reply enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java]: Fixed

File: enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java (hunk 13 above)
Comment (michal-rozehnal-w) [reply enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java]: It is final now
