### PR TITLE
Fix #1025: Java 21 Build Fails

### LINKED ISSUE #1025: Java 21 Build Fails
```
[ERROR] Errors: 
[ERROR]   StateMachineServiceTest.testChangeMachineStatesInBatch_noDocuments:65 » IllegalState java.lang.IllegalStateException: Illegal pop() with non-matching JdbcValuesSourceProcessingState
[ERROR]   StateMachineServiceTest.testChangeMachineStatesInBatch_submitting:57 » IllegalState Illegal pop() with non-matching JdbcValuesSourceProcessingState
```

### PR DESCRIPTION
**Pull request by banterCZ**
The target remains set to `maven.compiler.release=17`.

### CODE REVIEW

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/statemachine/service/StateMachineService.java [hunk 1]
```diff
@@ -126,7 +126,7 @@ public Message<OnboardingEvent> createMessage(OwnerId ownerId, String processId,
     @Transactional(readOnly = true)
     public void changeMachineStatesInBatch() {
         final AtomicInteger countFinished = new AtomicInteger(0);
-        try (Stream<IdentityVerificationEntity> stream = identityVerificationService.streamAllIdentityVerificationsToChangeState().parallel()) {
+        try (Stream<IdentityVerificationEntity> stream = identityVerificationService.streamAllIdentityVerificationsToChangeState()) {
               stream.filter(identityVerification -> identityVerification.getDocumentVerifications().stream()
```
Comment (banterCZ) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/statemachine/service/StateMachineService.java:130]: 🤔 The root cause is most probably lazy-loading in the filter. Shouldn't we fetch it instead?

Comment (banterCZ) [reply enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/statemachine/service/StateMachineService.java]: Let's rewrite the subselect.

**Review by romanstrobl — APPROVED** [review]
Great!
