### PR TITLE
Fix #475: OTP failed attempts counted for process

### LINKED ISSUE #475: OTP failed attempts counted for process
Failed OTP attempts are counted for process.

```java
int failedAttempts = onboardingOtpRepository.countFailedAttemptsByProcessIdAndType(processId, otpType);
```

https://github.com/wultra/enrollment-server/blob/aed8eed5e2e4a796b42c2bd967528ae5b22b0a03/enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/CommonOtpService.java#L85

It does not work for process restart with a new identity verification. When OTP attempts limit is reached, it is failing forever.

### PR DESCRIPTION
**Pull request by banterCZ**
Pgsl update script

```sql
alter table es_onboarding_otp add column
    identity_verification_id VARCHAR(36);

alter table es_onboarding_otp add FOREIGN KEY (identity_verification_id) REFERENCES es_identity_verification (id);
```

### CODE REVIEW

File: enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/OnboardingProcessLimitService.java [hunk 1]
```diff
@@ -67,9 +68,13 @@ public OnboardingProcessLimitService(
      * Increment error score for an onboarding process.
      * @param process Onboarding process entity.
      * @param error Onboarding process error.
+     * @param ownerId Owner identification.
      */
-    public OnboardingProcessEntity incrementErrorScore(OnboardingProcessEntity process, OnboardingProcessError error) {
-        process.setErrorScore(process.getErrorScore() + error.getErrorScore());
+    public OnboardingProcessEntity incrementErrorScore(final OnboardingProcessEntity process, final OnboardingProcessError error, final OwnerId ownerId) {
```
Comment (banterCZ) [inline enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/OnboardingProcessLimitService.java:73]: We should consider to put `OwnerId` into _MDC_ #483

File: enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/CommonOtpService.java [hunk 2]
```diff
@@ -68,21 +72,27 @@ public class CommonOtpService implements OtpService {
     public CommonOtpService(
             final OnboardingOtpRepository onboardingOtpRepository,
             final OnboardingProcessRepository onboardingProcessRepository,
+            final IdentityVerificationRepository identityVerificationRepository,
```
Comment (banterCZ) [inline enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/CommonOtpService.java:75]: I am not quite happy with separation of enrollment-server and onboarding server, but it is not target of this PR, may be improved later.

File: enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/CommonOtpService.java [hunk 3]
```diff
@@ -135,6 +145,17 @@ public OtpVerifyResponse verifyOtpCode(String processId, OwnerId ownerId, String
...
     }
 
+    private int fetchFailedAttemptsCount(final OnboardingProcessEntity process, final OtpType otpType) throws OnboardingProcessException {
+        if (otpType == OtpType.ACTIVATION) {
+            return onboardingOtpRepository.countFailedAttempts(process, otpType);
+        } else {
+            final String activationId = process.getActivationId();
+            final IdentityVerificationEntity identityVerification = identityVerificationRepository.findFirstByActivationIdOrderByTimestampCreatedDesc(activationId)
+                    .orElseThrow(() -> new OnboardingProcessException("Identity verification not found, activation ID: " + activationId));
+            return onboardingOtpRepository.countFailedAttempts(process, otpType, identityVerification);
```
Comment (banterCZ) [inline enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/CommonOtpService.java:155]: ℹ️ This is the main change of this PR. OTP failed attempts are count per the whole proces for ACTIVATION, and per process and identity verification (because of possible restart) for USER_VERIFICATION.

File: enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/database/entity/OnboardingOtpEntity.java [hunk 4]
```diff
@@ -61,6 +61,13 @@ public class OnboardingOtpEntity implements Serializable {
     @JoinColumn(name = "process_id", referencedColumnName = "id", nullable = false)
     private OnboardingProcessEntity process;
 
+    /**
+     * Not-null only for {@link OtpType#USER_VERIFICATION} when limit is needed to count not over the whole process.
+     */
+    @ManyToOne(fetch = FetchType.LAZY)
```
Comment (romanstrobl) [inline enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/database/entity/OnboardingOtpEntity.java:67]: Good idea. We should probably review whether the `LAZY` fetch type could be added elsewhere, too.

File: enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/CommonOtpService.java (hunk 2 above)
Comment (romanstrobl) [reply enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/CommonOtpService.java:75]: Ok.

File: enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/CommonOtpService.java (hunk 3 above)
Comment (romanstrobl) [reply enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/CommonOtpService.java:155]: Good.

**Review by romanstrobl — APPROVED** [review]
Nice cleanup of logic which was missing for the OTP type `USER_VERIFICATION`. I have one question - will the logic work correctly after deployment for existing rows which do not have `identity_verification_id` set for the OTP yet?

**Comment by banterCZ** [comment]
> Nice cleanup of logic which was missing for the OTP type `USER_VERIFICATION`. I have one question - will the logic work correctly after deployment for existing rows which do not have `identity_verification_id` set for the OTP yet?

It works only for new OTPs. But since we are not in production yet, there is no need of any db patch.
