### PR TITLE
Fix #512: Invalid state when app gets closed during onboarding

### LINKED ISSUE #512: Invalid state when app gets closed during onboarding
In case both sides of ID card get rejected, the following invalid state occurs (see log messages).

Both documents which were submitted for verification are in state `REJECTED`, however the application claims that there are not enough documents to change the identity verification state. When the application is restarted at this point the process cannot be completed and the user just sees the progress wheel.

```
Nov 08 18:34:45 PowerAuth-Dev tomcat9[3023321]: 2022-11-08 18:34:45.053  INFO 3023321 --- [   scheduling-1] .a.o.i.s.v.VerificationProcessingService : Finished verification of DocumentVerificationEntity(id=7a4f9d3f-51e7-4a6c-a3ee-0d31323a44a3, type=ID_CARD, uploadId=f18b6625f2a66358ef482dd4ef834c81) with status: REJECTED, OwnerId(activationId=2554096f-0bbb-465e-83d9-e87d98ed49ab, userId=mockuser_258963)
Nov 08 18:34:45 PowerAuth-Dev tomcat9[3023321]: 2022-11-08 18:34:45.054  INFO 3023321 --- [   scheduling-1] .a.o.i.s.v.VerificationProcessingService : Finished verification of DocumentVerificationEntity(id=009accec-3c21-47e3-8321-534b6ea8fccc, type=ID_CARD, uploadId=4a5188e618feed607e5eff4261a61478) with status: REJECTED, OwnerId(activationId=2554096f-0bbb-465e-83d9-e87d98ed49ab, userId=mockuser_258963)
Nov 08 18:34:45 PowerAuth-Dev tomcat9[3023321]: 2022-11-08 18:34:45.055 DEBUG 3023321 --- [   scheduling-1] c.w.a.o.s.g.d.RequiredDocumentTypesCheck : There is not enough accepted document yet for identity verification ID: 34967332-1f2e-4773-af27-b5ff09ac6254
```

Update: The same problem occurs when first document is `ACCEPTED`, `REJECTED` or `FAILED` and the app is restarted, because identity verification status does not correspond to document status.

### PR DESCRIPTION
**Pull request by banterCZ**

### CODE REVIEW

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationService.java [hunk 1]
```diff
@@ -212,16 +212,9 @@ public List<DocumentVerificationEntity> submitDocuments(DocumentSubmitRequest re
 
         final IdentityVerificationPhase phase = idVerification.getPhase();
         final IdentityVerificationStatus status = idVerification.getStatus();
-        if (phase == IdentityVerificationPhase.DOCUMENT_VERIFICATION && status == IdentityVerificationStatus.IN_PROGRESS) {
```
Comment (banterCZ) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationService.java:215]: This used to be a fix to allow uploading another document in different states. But we return to the previous behavior, to allow it only in `DOCUMENT_UPLOAD / IN_PROGESS`

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationService.java [hunk 2]
```diff
@@ -376,40 +352,85 @@ public void processDocumentVerificationResult(final OwnerId ownerId, final Ident
...
             final IdentityVerificationEntity idVerification,
-            final List<DocumentVerificationEntity> docVerifications,
+            final List<DocumentVerificationEntity> docVerificationsToProcess,
             final OwnerId ownerId) {
 
-        final IdentityVerificationPhase phase = IdentityVerificationPhase.DOCUMENT_VERIFICATION;
-        final Date now = ownerId.getTimestamp();
-        if (docVerifications.stream()
+        final String identityVerificationId = idVerification.getId();
+        // docVerificationsToProcess have been modified, so idVerification.getDocumentVerifications() must be reloaded to reflect these modifications
```
Comment (banterCZ) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationService.java:363]: 👀 This was a little bit tricky. Status of documents is change at `checkVerificationResult`, but these changes were not yet available in the 1st level cache to get them via `idVerification.getDocumentVerifications()`.
`allDocumentVerifications` represents all documents, `docVerificationsToProcess` just current step.

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationService.java [hunk 3]
```diff
@@ -376,40 +352,85 @@ public void processDocumentVerificationResult(final OwnerId ownerId, final Ident
...
+            final IdentityVerificationEntity idVerification,
+            final DocumentStatus status,
+            final OwnerId ownerId) {
+
+        docVerifications.stream()
+                .filter(docVerification -> docVerification.getStatus() == status)
+                .findAny()
+                .ifPresent(docVerification -> {
+                    logger.debug("At least one document is {}, ID: {}, {}", status, docVerification.getId(), ownerId);
+                    idVerification.setErrorDetail(docVerification.getRejectReason());
```
Comment (banterCZ) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationService.java:403]: - [ ] `ORA-12899: value too large for column "POWERAUTH"."ES_IDENTITY_VERIFICATION"."ERROR_DETAIL" (actual: 566, maximum: 256)`

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationService.java [hunk 4]
```diff
@@ -400,12 +402,27 @@ private void handleDocumentStatus(
                 .findAny()
                 .ifPresent(docVerification -> {
                     logger.debug("At least one document is {}, ID: {}, {}", status, docVerification.getId(), ownerId);
-                    idVerification.setErrorDetail(docVerification.getRejectReason());
+                    idVerification.setErrorDetail(fetchErrorDetailShort(docVerification));
```
Comment (romanstrobl) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationService.java:405]: This change is incorrect.

Please see:
https://github.com/wultra/enrollment-server/blob/develop/enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/database/entity/IdentityVerificationEntity.java#L50

We want to continue using errors like this in `IdentityVerificationEntity`, because the value may be consumed by DWH for reporting.

I realize there are many other cases when this is done incorrectly, but let's not spread this error. I will raise a ticket for the other cases.

**Review by romanstrobl — CHANGES_REQUESTED** [review]
We'll need to postpone approval of this pull request after tests are passing. See:
https://github.com/wultra/powerauth-tests/pull/137

**Comment by banterCZ** [comment]
Tests passed
