### PR TITLE
Fix #521: Error when exceeding maximum attempts for presence check

### LINKED ISSUE #521: Error when exceeding maximum attempts for presence check
It seems that state machine does not process failed presence check correctly.

```
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]: 2022-11-11 14:51:50.894 ERROR 3859511 --- [io-8080-exec-16] .w.a.o.s.i.CustomStateMachineInterceptor : Unexpected targetState=OnboardingState.PRESENCE_CHECK_IN_PROGRESS(phase=PRESENCE_CHECK, status=IN_PROGRESS) when expectedState=OnboardingState.PRESENCE_CHECK_FAILED(phase=PRESENCE_CHECK, status=FAILED), IdentityVerificationEntity(id=714d782e-ca33-4c9c-902e-66ee088e2f7d, activationId=6ad9011b-8711-4ee9-8a31-7ef77020b83d, status=FAILED, phase=PRESENCE_CHECK)
```

image

image

See log:

```
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]: 2022-11-11 14:51:50.891 ERROR 3859511 --- [io-8080-exec-16] .w.a.o.s.i.CustomStateMachineInterceptor : Error occurred in a state machine.
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]: com.wultra.app.onboardingserver.errorhandling.PresenceCheckLimitException: Max failed attempts reached for presence check, OwnerId(activationId=6ad9011b-8711-4ee9-8a31-7ef77020b83d, userId=mockuser_22222)
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at com.wultra.app.onboardingserver.impl.service.PresenceCheckLimitService.checkPresenceCheckMaxAttemptLimit(PresenceCheckLimitService.java:133) ~[classes/:1.4.0-SNAPSHOT]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at com.wultra.app.onboardingserver.impl.service.PresenceCheckService.init(PresenceCheckService.java:128) ~[classes/:1.4.0-SNAPSHOT]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at com.wultra.app.onboardingserver.impl.service.PresenceCheckService$$FastClassBySpringCGLIB$$e8f7e8d8.invoke(<generated>) ~[classes/:1.4.0-SNAPSHOT]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at com.wultra.app.onboardingserver.impl.service.PresenceCheckService$$EnhancerBySpringCGLIB$$896fb00d.init(<generated>) ~[classes/:1.4.0-SNAPSHOT]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at com.wultra.app.onboardingserver.statemachine.action.presencecheck.PresenceCheckInitAction.execute(PresenceCheckInitAction.java:59) ~[classes/:1.4.0-SNAPSHOT]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.statemachine.action.Actions.lambda$null$0(Actions.java:98) ~[spring-statemachine-core-3.2.0.jar:3.2.0]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoRunnable.call(MonoRunnable.java:73) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoRunnable.call(MonoRunnable.java:32) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:252) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.Mono.subscribe(Mono.java:4397) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:272) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:230) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:165) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:87) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.Mono.subscribe(Mono.java:4397) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoSupplier.subscribe(MonoSupplier.java:62) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.Mono.subscribe(Mono.java:4397) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoSupplier.subscribe(MonoSupplier.java:62) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:240) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onComplete(FluxMapFuseable.java:152) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2400) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:171) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onSubscribe(MonoIgnoreThen.java:134) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.Mono.subscribe(Mono.java:4397) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.Mono.subscribe(Mono.java:4397) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.tryOnNext(FluxFilterFuseable.java:148) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxIterable$IterableSubscriptionConditional.slowPath(FluxIterable.java:574) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxIterable$IterableSubscriptionConditional.request(FluxIterable.java:532) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.request(FluxFilterFuseable.java:191) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onSubscribe(FluxFilterFuseable.java:87) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:161) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:87) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.Mono.subscribe(Mono.java:4397) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoIgnorePublisher.subscribe(MonoIgnorePublisher.java:57) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.Mono.subscribe(Mono.java:4397) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoWhen$WhenCoordinator.subscribe(MonoWhen.java:160) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoWhen.subscribe(MonoWhen.java:99) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.Mono.subscribe(Mono.java:4397) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:537) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.EmitterProcessor.tryEmitNext(EmitterProcessor.java:343) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:100) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.statemachine.support.ReactiveStateMachineExecutor.lambda$null$4(ReactiveStateMachineExecutor.java:207) ~[spring-statemachine-core-3.2.0.jar:3.2.0]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoRunnable.subscribe(MonoRunnable.java:49) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:77) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.Mono.subscribe(Mono.java:4382) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFlatMap$FlatMapMain.tryEmit(FluxFlatMap.java:543) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFlatMap$FlatMapInner.onNext(FluxFlatMap.java:984) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:712) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:588) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFlatMap$FlatMapInner.onSubscribe(FluxFlatMap.java:955) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:192) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.Mono.subscribe(Mono.java:4382) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.tryOnNext(FluxFilterFuseable.java:148) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.tryOnNext(FluxFilterFuseable.java:367) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxIterable$IterableSubscriptionConditional.slowPath(FluxIterable.java:574) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxIterable$IterableSubscriptionConditional.request(FluxIterable.java:532) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.request(FluxFilterFuseable.java:411) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.request(FluxFilterFuseable.java:191) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onSubscribe(FluxFilterFuseable.java:87) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onSubscribe(FluxFilterFuseable.java:305) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:161) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:87) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.Mono.subscribe(Mono.java:4397) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFlatMap$FlatMapMain.tryEmitScalar(FluxFlatMap.java:488) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:421) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxArray$ArraySubscription.slowPath(FluxArray.java:127) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxArray$ArraySubscription.request(FluxArray.java:100) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxMerge.subscribe(FluxMerge.java:70) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.Mono.subscribe(Mono.java:4397) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoWhen$WhenCoordinator.subscribe(MonoWhen.java:160) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoWhen.subscribe(MonoWhen.java:99) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.Mono.subscribe(Mono.java:4397) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.Mono.subscribe(Mono.java:4397) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:203) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.Mono.subscribe(Mono.java:4382) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.tryOnNext(FluxFilterFuseable.java:148) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.tryOnNext(FluxFilterFuseable.java:367) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxIterable$IterableSubscriptionConditional.slowPath(FluxIterable.java:574) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxIterable$IterableSubscriptionConditional.request(FluxIterable.java:532) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.request(FluxFilterFuseable.java:411) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.request(FluxFilterFuseable.java:191) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onSubscribe(FluxFilterFuseable.java:87) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onSubscribe(FluxFilterFuseable.java:305) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:161) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:87) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.Mono.subscribe(Mono.java:4397) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:258) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxConcatArray.subscribe(FluxConcatArray.java:78) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.Flux.subscribe(Flux.java:8466) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:200) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoFlatMapMany.subscribeOrReturn(MonoFlatMapMany.java:49) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFromMonoOperator.subscribe(FluxFromMonoOperator.java:76) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.Flux.subscribe(Flux.java:8466) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:195) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:171) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onSubscribe(MonoFlatMapMany.java:141) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.Flux.subscribe(Flux.java:8466) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:200) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.MonoFlatMapMany.subscribeOrReturn(MonoFlatMapMany.java:49) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.Flux.subscribe(Flux.java:8452) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at reactor.core.publisher.Flux.blockLast(Flux.java:2644) ~[reactor-core-3.4.22.jar:3.4.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at com.wultra.app.onboardingserver.statemachine.service.StateMachineService.sendEventMessage(StateMachineService.java:173) ~[classes/:1.4.0-SNAPSHOT]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at com.wultra.app.onboardingserver.statemachine.service.StateMachineService.processStateMachineEvent(StateMachineService.java:99) ~[classes/:1.4.0-SNAPSHOT]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at com.wultra.app.onboardingserver.statemachine.service.StateMachineService$$FastClassBySpringCGLIB$$232d3225.invoke(<generated>) ~[classes/:1.4.0-SNAPSHOT]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at com.wultra.app.onboardingserver.statemachine.service.StateMachineService$$EnhancerBySpringCGLIB$$ed4414.processStateMachineEvent(<generated>) ~[classes/:1.4.0-SNAPSHOT]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at com.wultra.app.onboardingserver.impl.service.IdentityVerificationRestService.initPresenceCheck(IdentityVerificationRestService.java:379) ~[classes/:1.4.0-SNAPSHOT]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at com.wultra.app.onboardingserver.impl.service.IdentityVerificationRestService$$FastClassBySpringCGLIB$$3864bad8.invoke(<generated>) ~[classes/:1.4.0-SNAPSHOT]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at com.wultra.app.onboardingserver.impl.service.IdentityVerificationRestService$$EnhancerBySpringCGLIB$$1149660d.initPresenceCheck(<generated>) ~[classes/:1.4.0-SNAPSHOT]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at com.wultra.app.onboardingserver.controller.api.IdentityVerificationController.initPresenceCheck(IdentityVerificationController.java:244) ~[classes/:1.4.0-SNAPSHOT]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1070) ~[spring-webmvc-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) ~[tomcat9-servlet-api-9.0.31.jar:na]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat9-servlet-api-9.0.31.jar:na]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:111) ~[spring-web-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at io.getlime.security.powerauth.rest.api.spring.filter.PowerAuthRequestFilter.doFilterInternal(PowerAuthRequestFilter.java:43) ~[powerauth-restful-security-spring-annotation-1.4.0-SNAPSHOT.jar:na]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat9-websocket-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.web.filter.AbstractRequestLoggingFilter.doFilterInternal(AbstractRequestLoggingFilter.java:289) ~[spring-web-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.web.servlet.resource.ResourceUrlEncodingFilter.doFilter(ResourceUrlEncodingFilter.java:67) ~[spring-webmvc-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:337) ~[spring-security-web-5.6.7.jar:5.6.7]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:122) ~[spring-security-web-5.6.7.jar:5.6.7]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:116) ~[spring-security-web-5.6.7.jar:5.6.7]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.6.7.jar:5.6.7]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126) ~[spring-security-web-5.6.7.jar:5.6.7]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81) ~[spring-security-web-5.6.7.jar:5.6.7]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.6.7.jar:5.6.7]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:109) ~[spring-security-web-5.6.7.jar:5.6.7]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.6.7.jar:5.6.7]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149) ~[spring-security-web-5.6.7.jar:5.6.7]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.6.7.jar:5.6.7]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[spring-security-web-5.6.7.jar:5.6.7]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.6.7.jar:5.6.7]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103) ~[spring-security-web-5.6.7.jar:5.6.7]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89) ~[spring-security-web-5.6.7.jar:5.6.7]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.6.7.jar:5.6.7]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) ~[spring-security-web-5.6.7.jar:5.6.7]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) ~[spring-security-web-5.6.7.jar:5.6.7]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.6.7.jar:5.6.7]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110) ~[spring-security-web-5.6.7.jar:5.6.7]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80) ~[spring-security-web-5.6.7.jar:5.6.7]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.6.7.jar:5.6.7]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55) ~[spring-security-web-5.6.7.jar:5.6.7]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.6.7.jar:5.6.7]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221) ~[spring-security-web-5.6.7.jar:5.6.7]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:186) ~[spring-security-web-5.6.7.jar:5.6.7]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354) ~[spring-web-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267) ~[spring-web-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96) ~[spring-boot-actuator-2.6.11.jar:2.6.11]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:126) ~[spring-boot-2.6.11.jar:2.6.11]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:64) ~[spring-boot-2.6.11.jar:2.6.11]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:101) ~[spring-boot-2.6.11.jar:2.6.11]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:119) ~[spring-boot-2.6.11.jar:2.6.11]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.22.jar:5.3.22]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:375) ~[tomcat9-coyote-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat9-coyote-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) ~[tomcat9-coyote-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639) ~[tomcat9-coyote-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat9-coyote-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat9-util-9.0.31.jar:9.0.31]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]:         at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]: 2022-11-11 14:51:50.894 DEBUG 3859511 --- [io-8080-exec-16] c.w.a.o.statemachine.StateMachineConfig  : State changed from OnboardingState.PRESENCE_CHECK_NOT_INITIALIZED(phase=PRESENCE_CHECK, status=NOT_INITIALIZED) to OnboardingState.PRESENCE_CHECK_IN_PROGRESS(phase=PRESENCE_CHECK, status=IN_PROGRESS)
Nov 11 14:51:50 PowerAuth-Dev tomcat9[3859511]: 2022-11-11 14:51:50.894 ERROR 3859511 --- [io-8080-exec-16] .w.a.o.s.i.CustomStateMachineInterceptor : Unexpected targetState=OnboardingState.PRESENCE_CHECK_IN_PROGRESS(phase=PRESENCE_CHECK, status=IN_PROGRESS) when expectedState=OnboardingState.PRESENCE_CHECK_FAILED(phase=PRESENCE_CHECK, status=FAILED), IdentityVerificationEntity(id=714d782e-ca33-4c9c-902e-66ee088e2f7d, activationId=6ad9011b-8711-4ee9-8a31-7ef77020b83d, status=FAILED, phase=PRESENCE_CHECK)
```

### PR DESCRIPTION
**Pull request by banterCZ**

### CODE REVIEW

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/statemachine/interceptor/CustomStateMachineInterceptor.java [hunk 1]
```diff
@@ -60,23 +60,33 @@ public Exception stateMachineError(StateMachine<OnboardingState, OnboardingEvent
...
         } else if (e instanceof PresenceCheckException) {
-            logger.warn("Presence check failed", e);
+            logger.warn("Presence check failed: {}", e.getMessage());
+            logger.debug("Presence check failed", e);
             response = new ErrorResponse("PRESENCE_CHECK_FAILED", "Presence check failed.");
             status = HttpStatus.BAD_REQUEST;
+        } else if (e instanceof PresenceCheckLimitException) {
+            logger.warn("Presence check limit reached: {}", e.getMessage());
+            logger.debug("Presence check limit reached", e);
+            response = new ErrorResponse("PRESENCE_CHECK_LIMIT_REACHED", "Presence check limit reached.");
```
Comment (banterCZ) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/statemachine/interceptor/CustomStateMachineInterceptor.java:85]: @kober32 FYI `429/PRESENCE_CHECK_LIMIT_REACHED`

**Review by romanstrobl — APPROVED** [review]
Excellent!
