### PR TITLE
Fix #269: Separate OTP failure handling by OTP type

### LINKED ISSUE #269: Separate OTP failure handling by OTP type
The event for maximum number of OTP verification failures should have different handling based on OTP type:
- `ACTIVATION` - onboarding process fails
- `USER_VERIFICATION` - identity verification fails unless the max. limit of identity verifications has been exceeded, in this case the onboarding process fails

### PR DESCRIPTION
**Pull request by romanstrobl**
This pull request contains following changes which are required for https://github.com/wultra/enrollment-server/issues/269:
- identity verification restart in case `maxFailedAttemptsOtp` is reached
- OTP verification during SCA step allows multiple OTP verification attempts instead of just one
- improved calculation of remaining attempts for OTP verification
- refactoring of entity, repository and service classes into `common` module due to dependencies for the identity verification restart logic

### CODE REVIEW

File: enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/CommonOtpService.java [hunk 1]
```diff
@@ -121,7 +129,11 @@ public OtpVerifyResponse verifyOtpCode(String processId, OwnerId ownerId, String
         response.setOnboardingStatus(process.getStatus());
         response.setExpired(expired);
         response.setVerified(verified);
-        response.setRemainingAttempts(maxFailedAttempts - failedAttempts);
+        if (otp.getStatus() == OtpStatus.ACTIVE) {
```
Comment (banterCZ) [inline enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/CommonOtpService.java:132]: Nit: Or could be extracted to a method and use `response.setRemainingAttempts(calculateRemainingAttempts(otp))`

File: enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/CommonOtpService.java [hunk 2]
```diff
@@ -146,8 +158,8 @@ private void handleFailedOtpVerification(OnboardingProcessEntity process, OwnerI
             otp.setTimestampFailed(ownerId.getTimestamp());
             onboardingOtpRepository.save(otp);
 
-            // Onboarding process is failed, update it
-            process = processLimitService.failProcess(process, OnboardingOtpEntity.ERROR_MAX_FAILED_ATTEMPTS, ErrorOrigin.PROCESS_LIMIT_CHECK);
+            // Fail process or identity verification based on OTP type
+            handleOtpMaxFailedAttempts(process, otp, ownerId);
```
Comment (banterCZ) [inline enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/CommonOtpService.java:162]: Nit: Here we have three information, an inline comment, a method name and javadoc. I guess we may omit the inline comment and rename a method, if you wish, for example to `failProcessOrIdentityVerification(process, otp, ownerId)`.

File: enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/CommonOtpService.java [hunk 3]
```diff
@@ -172,4 +184,30 @@ private void handleFailedOtpVerification(OnboardingProcessEntity process, OwnerI
...
+     * @param ownerId Owner identification.
+     * @return Updated onboarding process entity.
+     */
+    private OnboardingProcessEntity handleOtpMaxFailedAttempts(OnboardingProcessEntity process, OnboardingOtpEntity otp, OwnerId ownerId) {
+        if (otp.getType() == OtpType.USER_VERIFICATION) {
+            // Reset current identity verification, if possible. The process may
+            try {
+                verificationLimitService.resetIdentityVerification(ownerId);
+            } catch (RemoteCommunicationException | IdentityVerificationException | OnboardingProcessLimitException | OnboardingProcessException ex) {
+                logger.error("Identity verification reset failed, error: " + ex.getMessage(), ex);
```
Comment (banterCZ) [inline enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/CommonOtpService.java:200]: Nit: May be written as `logger.error("Identity verification reset failed, error: {}", ex.getMessage(), ex);`

File: enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/CommonOtpService.java [hunk 4]
```diff
@@ -172,4 +184,30 @@ private void handleFailedOtpVerification(OnboardingProcessEntity process, OwnerI
...
+    /**
+     * Handle maximum failed attempts for OTP verification based on OTP type.
+     * @param process Onboarding process.
+     * @param otp Onboarding OTP.
+     * @param ownerId Owner identification.
+     * @return Updated onboarding process entity.
+     */
+    private OnboardingProcessEntity handleOtpMaxFailedAttempts(OnboardingProcessEntity process, OnboardingOtpEntity otp, OwnerId ownerId) {
+        if (otp.getType() == OtpType.USER_VERIFICATION) {
+            // Reset current identity verification, if possible. The process may
```
Comment (banterCZ) [inline enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/CommonOtpService.java:196]: I did not get the comment. What may the process do?

File: enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/CommonOtpService.java [hunk 5]
```diff
@@ -172,4 +184,30 @@ private void handleFailedOtpVerification(OnboardingProcessEntity process, OwnerI
...
+            try {
+                verificationLimitService.resetIdentityVerification(ownerId);
+            } catch (RemoteCommunicationException | IdentityVerificationException | OnboardingProcessLimitException | OnboardingProcessException ex) {
+                logger.error("Identity verification reset failed, error: " + ex.getMessage(), ex);
+                // Obtain most current process entity, the process may have failed due to reached limit of identity verification resets
+                Optional <OnboardingProcessEntity> updatedProcessOptional = onboardingProcessRepository.findById(process.getId());
+                if (updatedProcessOptional.isPresent()) {
```
Comment (banterCZ) [inline enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/CommonOtpService.java:203]: 🤔 So may it happen that the process is not found and we return the old reference? Shouldn't we throw an exception?

File: enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/IdentityVerificationLimitService.java [hunk 6]
```diff
@@ -132,17 +127,64 @@ public void checkIdentityVerificationLimit(OwnerId ownerId) throws RemoteCommuni
...
+     * Reset identity verification by setting activation flag to VERIFICATION_PENDING.
+     *
+     * @param ownerId Owner identification.
+     * @throws RemoteCommunicationException Thrown when communication with PowerAuth server fails.
+     * @throws IdentityVerificationException Thrown when identity verification reset fails.
+     * @throws OnboardingProcessLimitException Thrown when maximum failed attempts for identity verification have been reached.
+     * @throws OnboardingProcessException Thrown when onboarding process is invalid.
+     */
+    public void resetIdentityVerification(OwnerId ownerId) throws RemoteCommunicationException, IdentityVerificationException, OnboardingProcessLimitException, OnboardingProcessException {
+        Optional<OnboardingProcessEntity> processOptional = onboardingProcessRepository.findProcessByActivationId(ownerId.getActivationId());
```
Comment (banterCZ) [inline enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/IdentityVerificationLimitService.java:153]: Nit: I prefer this idiom
```java
final OnboardingProcessEntity process = onboardingProcessRepository.findProcessByActivationId(ownerId.getActivationId()).orElseThrow(() ->
    new OnboardingProcessException("Onboarding process not found, activation ID: " + ownerId.getActivationId()));
```

File: enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/IdentityVerificationLimitService.java [hunk 7]
```diff
@@ -132,17 +127,64 @@ public void checkIdentityVerificationLimit(OwnerId ownerId) throws RemoteCommuni
...
+     * @param ownerId Owner identification.
+     * @throws OnboardingProcessLimitException Exception thrown due to failed process.
+     * @throws RemoteCommunicationException Thrown when communication with PowerAuth server fails.
+     */
+    private void handleFailedProcess(OwnerId ownerId) throws OnboardingProcessLimitException, RemoteCommunicationException {
+        // Remove flag VERIFICATION_IN_PROGRESS and add VERIFICATION_PENDING flag
+        activationFlagService.updateActivationFlagsForFailedIdentityVerification(ownerId);
+
+        logger.warn("Max error score reached for onboarding process, {}.", ownerId);
+        throw new OnboardingProcessLimitException("Max error score reached for onboarding process");
```
Comment (banterCZ) [inline enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/IdentityVerificationLimitService.java:187]: Shouldn't we add the process ID to the log message and/or exception message? Anyway, I would omit the logger, because is it logged at the controller level, isn't?

**Review by banterCZ — APPROVED** [review]
I have just little comments to consider.

File: enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/CommonOtpService.java (hunk 1 above)
Comment (romanstrobl) [reply enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/CommonOtpService.java:132]: Sure, why not.

File: enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/CommonOtpService.java (hunk 2 above)
Comment (romanstrobl) [reply enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/CommonOtpService.java:162]: Ok.

File: enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/CommonOtpService.java (hunk 3 above)
Comment (romanstrobl) [reply enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/CommonOtpService.java:200]: I will change it.

File: enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/CommonOtpService.java (hunk 5 above)
Comment (romanstrobl) [reply enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/CommonOtpService.java:203]: This is basically impossible, but ok, we can handle it.

File: enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/IdentityVerificationLimitService.java (hunk 6 above)
Comment (romanstrobl) [reply enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/IdentityVerificationLimitService.java:153]: Ok, I can change it.

File: enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/IdentityVerificationLimitService.java (hunk 7 above)
Comment (romanstrobl) [reply enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/service/IdentityVerificationLimitService.java:187]: I will update the message with more details and avoid logging twice.
