### PR TITLE
Fix #1074: Tests are failing in parallel maven build

### LINKED ISSUE #1074: Tests are failing in parallel maven build
Parallel maven build `mvn package -T 1C` or `mvnd package` fails because of already used port.

### PR DESCRIPTION
**Pull request by banterCZ**

### CODE REVIEW

File: enrollment-server-onboarding-provider-innovatrics/src/test/java/com/wultra/app/onboardingserver/provider/innovatrics/InnovatricsRestApiServiceTest.java [hunk 1]
```diff
@@ -51,7 +51,8 @@
 @ActiveProfiles("test")
 class InnovatricsRestApiServiceTest {
 
-    static final int PORT = 52936;
+    // TODO (racansky, 2024-06-17) find the way how to set the same random port for mock server and property
+    static final int PORT = 52937;
```
Comment (banterCZ) [inline enrollment-server-onboarding-provider-innovatrics/src/test/java/com/wultra/app/onboardingserver/provider/innovatrics/InnovatricsRestApiServiceTest.java:55]: It used to be in collision with `ZenidRestApiServiceTest`. Just a quick fix. Random ports will be handled later on.

**Review by jnpsk — APPROVED** [review]
