### PR TITLE
Fix #1547: Add parsing for PlaceOfBirth

### LINKED ISSUE #1547: PlaceOfBirth is not parsed from document extraction
### Affected product(s) and version(s)

_No response_

### Environment

_No response_

### Steps to reproduce, current result, expected result

Scan document witj PlaceOfBirth
Sent for evaluation

Expected result:

Actual result:

The class MicroblinkExtractedDataParser doesn't parse this value

### Log output

_No response_

### PR DESCRIPTION
**Pull request by michal-rozehnal-w**

### CODE REVIEW

File: enrollment-server-onboarding-provider-microblink/src/test/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkExtractedDataParserTest.java [hunk 1]
```diff
@@ -0,0 +1,139 @@
...
+
+    private MicroblinkExtractedDataParser tested;
+
+    @BeforeEach
+    void setUp() {
+        tested = new MicroblinkExtractedDataParser(MAPPER);
+    }
+
+    @ParameterizedTest
+    @NullAndEmptySource
```
Comment (michal-rozehnal-w) [inline enrollment-server-onboarding-provider-microblink/src/test/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkExtractedDataParserTest.java:66]: Kudos to AI—I didn’t know there was such an annotation.

File: enrollment-server-onboarding-provider-microblink/src/test/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkExtractedDataParserTest.java [hunk 2]
```diff
@@ -0,0 +1,139 @@
...
+        return """
+                {"givenNames":null,"surname":null,"dateOfBirth":null,"placeOfBirth":null,"country":null,"sex":null,"nationality":null,"personalNumber":null,"documentNumber":null,"dateOfIssue":null,"dateOfExpiry":null,"authority":null}""";
+    }
+
+    private static String buildExpectedEmptyResultWithAllValues() {
+        return """
+                {"givenNames":"PRENUMELE","surname":"NUMELE","dateOfBirth":"1999-12-24","placeOfBirth":"Prague","country":"MDA","sex":"X","nationality":"Moldovan","personalNumber":"816008/0610","documentNumber":"EA0000000","dateOfIssue":"2012-01-10","dateOfExpiry":"2025-10-13","authority":"Chisinau A"}""";
+    }
+
+    @SneakyThrows
```
Comment (michal-rozehnal-w) [inline enrollment-server-onboarding-provider-microblink/src/test/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkExtractedDataParserTest.java:124]: IMHO acceptable for tests

File: enrollment-server-onboarding-provider-microblink/src/test/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkExtractedDataParserTest.java [hunk 3]
```diff
@@ -0,0 +1,139 @@
+/*
+ * PowerAuth Enrollment Server
+ * Copyright (C) 2026 Wultra s.r.o.
```
[the remark this answers is not in the document]
Comment (michal-rozehnal-w) [reply enrollment-server-onboarding-provider-microblink/src/test/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkExtractedDataParserTest.java:3]: The year is correct because I created the class today

File: enrollment-server-onboarding-provider-microblink/src/test/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProviderIntTest.java [hunk 4]
```diff
@@ -419,7 +419,7 @@ void testCleanupDocuments_verificationDataFound_allDocumentDataAreDeleted() {
     }
 
     @Test
-    void testVerifyDocuments_successfulVerification_correctResponseIsReturned() throws DocumentVerificationException, RemoteCommunicationException {
+    void testVerifyDocuments_successfulVerification_correctResponseIsReturned() throws DocumentVerificationException {
```
Comment (banterCZ) [inline enrollment-server-onboarding-provider-microblink/src/test/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProviderIntTest.java]: Nitpick: For tests, I do not care and use just `throws Exception`.

**Review by banterCZ — APPROVED** [review]

File: enrollment-server-onboarding-provider-microblink/src/test/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProviderIntTest.java (hunk 4 above)
Comment (michal-rozehnal-w) [reply enrollment-server-onboarding-provider-microblink/src/test/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProviderIntTest.java]: True, for tests specific type doesn't matter. I updated test methods in the class
