### PR TITLE
Fix #1467: Fetch consent fails when the process in ACTIVATION_IN_PROG…

### LINKED ISSUE #1467: Fetch consent fails when the process in ACTIVATION_IN_PROGRESS
### Affected product(s) and version(s)

_No response_

### Environment

_No response_

### Steps to reproduce, current result, expected result

Fetch consent fails when the process is in `ACTIVATION_IN_PROGRESS`

### Log output

_No response_

### PR DESCRIPTION
**Pull request by banterCZ**

### CODE REVIEW

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationRestService.java [hunk 1]
```diff
@@ -672,7 +672,7 @@ public ObjectResponse<OnboardingConsentTextResponse> fetchConsentText(
         logger.debug("Returning consent for {}", requestObject);
         OnboardingConsentTextRequestValidator.validate(requestObject);
 
-        final OwnerId ownerId = extractOwnerId(apiAuthentication);
+        final OwnerId ownerId = PowerAuthUtil.getOwnerId(apiAuthentication);
```
Comment (michal-rozehnal-w) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationRestService.java:675]: Just note that `PowerAuthUtil#getOwnerId` does not check the `OnboardingStatus`, which is fine in my opinion, since calling this endpoint is independent of the onboarding process state (it doesn't move it to the next state).

**Review by michal-rozehnal-w — APPROVED** [review]

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationRestService.java (hunk 1 above)
Comment (banterCZ) [reply enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationRestService.java:675]: You are right, but we are verifying the process status three lines below.

```java
onboardingService.verifyProcessId(ownerId, processId, OnboardingStatus.NOT_YET_COMPLETED);
```
