### PR TITLE
Fix #496: Identity verification may not continue in case of provider error during final validation

### LINKED ISSUE #496: Identity verification may not continue in case of provider error during final validation
In case the document verification provider method `verifyDocuments` in identity verification state `DOCUMENT_VERIFICATION_FINAL/IN_PROGRESS` throws an exception, the user may get stuck on this step. I think we want to introduce this step into the proper state machine handling and increment error score with each failure, then the identity verification will fail after the score exceeeds maximum limit.

### PR DESCRIPTION
**Pull request by banterCZ**

### CODE REVIEW

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/statemachine/action/clientevaluation/ClientEvaluationInitAction.java [hunk 1]
```diff
@@ -16,41 +16,36 @@
...
-    public void execute(final StateContext<OnboardingState, OnboardingEvent> context) {
-        final OwnerId ownerId = (OwnerId) context.getMessageHeader(EventHeaderName.OWNER_ID);
-        final IdentityVerificationEntity identityVerification = context.getExtendedState().get(ExtendedStateVariable.IDENTITY_VERIFICATION, IdentityVerificationEntity.class);
-
-        clientEvaluationService.initClientEvaluation(ownerId, identityVerification);
+    protected IdentityVerificationStatus getStatus() {
+        return IN_PROGRESS;
+    }
 
-        ActionUtil.sendNextStateEvent(context);
```
Comment (banterCZ) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/statemachine/action/clientevaluation/ClientEvaluationInitAction.java:54]: This sending event in the middle of process was quite pre-mature. Let's postpone it for a while

File: enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/database/IdentityVerificationRepository.java [hunk 2]
```diff
@@ -64,6 +64,12 @@ public interface IdentityVerificationRepository extends CrudRepository<IdentityV
             "   AND id.status = com.wultra.app.enrollmentserver.model.enumeration.IdentityVerificationStatus.VERIFICATION_PENDING)" +
             " OR (id.phase = com.wultra.app.enrollmentserver.model.enumeration.IdentityVerificationPhase.DOCUMENT_VERIFICATION" +
             "   AND id.status = com.wultra.app.enrollmentserver.model.enumeration.IdentityVerificationStatus.ACCEPTED)" +
+            " OR (id.phase = com.wultra.app.enrollmentserver.model.enumeration.IdentityVerificationPhase.DOCUMENT_VERIFICATION_FINAL" +
+            "   AND id.status = com.wultra.app.enrollmentserver.model.enumeration.IdentityVerificationStatus.IN_PROGRESS)" +
+            " OR (id.phase = com.wultra.app.enrollmentserver.model.enumeration.IdentityVerificationPhase.DOCUMENT_VERIFICATION_FINAL" +
+            "   AND id.status = com.wultra.app.enrollmentserver.model.enumeration.IdentityVerificationStatus.ACCEPTED)" +
+            " OR (id.phase = com.wultra.app.enrollmentserver.model.enumeration.IdentityVerificationPhase.CLIENT_EVALUATION" +
```
Comment (banterCZ) [inline enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/database/IdentityVerificationRepository.java:71]: We stopped sending an event in the middle of process, so let's keep all verifications states to change here.

File: enrollment-server-onboarding/src/test/java/com/wultra/app/onboardingserver/statemachine/DocumentVerificationTransitionsTest.java [hunk 3]
```diff
@@ -143,14 +140,7 @@ private void testDocumentVerificationStatus(IdentityVerificationStatus identityS
     }
 
     private IdentityVerificationEntity createIdentityVerificationLocal(IdentityVerificationPhase phase, IdentityVerificationStatus status) {
-        final DocumentVerificationEntity documentVerification = new DocumentVerificationEntity();
```
Comment (banterCZ) [inline enrollment-server-onboarding/src/test/java/com/wultra/app/onboardingserver/statemachine/DocumentVerificationTransitionsTest.java:146]: This was introduced in #501 but not needed anymore, because now we end at `DOCUMENT_VERIFICATION_FINAL_IN_PROGRESS` (no event is triggered internally).

**Review by romanstrobl — APPROVED** [review]
Approved, let's test this change thoroughly.
