### PR TITLE
Fix #757: Communication with dev ZenID is not working

### LINKED ISSUE #757: Communication with dev ZenID is not working
In mobile tokens start, identity verification.
Pick the documents - any allowed combination

Expected results: Proceed to the scanning of documents.
Actual result: Error.

Note the underlying error message on dev environment:

```
Caused by: com.wultra.core.rest.client.base.RestClientException: HTTP GET request failed
        at com.wultra.core.rest.client.base.DefaultRestClient.get(DefaultRestClient.java:251) ~[rest-client-base-1.7.0-SNAPSHOT.jar:na]
        at com.wultra.app.onboardingserver.docverify.zenid.service.ZenidRestApiService.initSdk(ZenidRestApiService.java:224) ~[classes/:1.5.0-SNAPSHOT]
        at com.wultra.app.onboardingserver.docverify.zenid.provider.ZenidDocumentVerificationProvider.initVerificationSdk(ZenidDocumentVerificationProvider.java:339) ~[classes/:1.5.0-SNAPSHOT]
        ... 145 common frames omitted
Caused by: org.springframework.core.codec.DecodingException: JSON decoding error: Unrecognized field "ProcessingTimeMs" (class com.wultra.app.onboardingserver.docverify.zenid.model.api.ZenidWebInitSdkResponse), not marked as ignorable
        at org.springframework.http.codec.json.AbstractJackson2Decoder.processException(AbstractJackson2Decoder.java:273) ~[spring-web-6.0.7.jar:6.0.7]
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
```
We should ignore new unrecognized fields.

### PR DESCRIPTION
**Pull request by banterCZ**

### CODE REVIEW

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/docverify/zenid/config/ZenidConfig.java [hunk 1]
```diff
@@ -53,7 +53,8 @@ public class ZenidConfig {
     );
 
     public static final Map<DeserializationFeature, Boolean> DESERIALIZATION_FEATURES = Map.of(
-            DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE, false
+            DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE, false,
+            DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false
```
Comment (banterCZ) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/docverify/zenid/config/ZenidConfig.java:57]: @zcgandcomp has suggested merging these default features with values defined in the property file.

**Review by petrdvorak — APPROVED** [review]
Looks OK
