### PR TITLE
Fix #260: Implement time limit for onboarding process

### LINKED ISSUE #260: Implement time limit for onboarding process
The onboarding limit should have a time limit with a default value of 3 hours. When the time limit is exceeded, the onboarding process fails.

### PR DESCRIPTION
**Pull request by romanstrobl**
This pull request updates the limit checks:
- added new limit for overall process timeout
- time limits refactored to `Duration`
- updated default expiration constants (shortened identity verification, migration to `Duration` format)
- updated constants for `error_detail` to obtain more exact reason of failure
- a new "dummy" failed process is created when the daily process limit is exceeded, so that the error is persisted in database

### CODE REVIEW

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/configuration/IdentityVerificationConfig.java [hunk 1]
```diff
@@ -51,11 +53,11 @@ public class IdentityVerificationConfig {
     @Value("${enrollment-server-onboarding.presence-check.cleanupEnabled:false}")
     private boolean presenceCheckCleanupEnabled;
 
-    @Value("${enrollment-server-onboarding.identity-verification.data-retention.hours:1}")
-    private int dataRetentionTime;
+    @Value("${enrollment-server-onboarding.identity-verification.data-retention.hours:PT1H}")
```
Comment (saalistaja) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/configuration/IdentityVerificationConfig.java:56]: I guess we can use also the basic format as `1h` here

https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config.typesafe-configuration-properties.conversion.durations

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/configuration/IdentityVerificationConfig.java [hunk 2]
```diff
@@ -51,11 +53,11 @@ public class IdentityVerificationConfig {
...
+    private Duration dataRetentionTime;
 
-    @Value("${enrollment-server-onboarding.onboarding-process.verification.expiration.seconds:300}")
-    private int verificationExpirationTime;
+    @Value("${enrollment-server-onboarding.onboarding-process.verification.expiration:PT1H}")
```
Comment (saalistaja) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/configuration/IdentityVerificationConfig.java]: Shouldn't be `5m` here?

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/configuration/IdentityVerificationConfig.java (hunk 1 above)
Comment (romanstrobl) [reply enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/configuration/IdentityVerificationConfig.java:56]: Sure, we can, but I will update it in all occurrences.

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/OnboardingServiceImpl.java [hunk 3]
```diff
@@ -139,6 +133,20 @@ public OnboardingStartResponse startOnboarding(OnboardingStartRequest request) t
...
+        // Check for brute force attacks
+        Calendar c = GregorianCalendar.getInstance();
+        c.add(Calendar.HOUR, -24);
+        Date timestampCheckStart = c.getTime();
+        int existingProcessCount = onboardingProcessRepository.countProcessesAfterTimestamp(userId, timestampCheckStart);
+        if (existingProcessCount > onboardingConfig.getMaxProcessCountPerDay()) {
+            process.setStatus(OnboardingStatus.FAILED);
+            process.setErrorDetail(ERROR_TOO_MANY_PROCESSES_PER_USER);
+            onboardingProcessRepository.save(process);
+            logger.warn("Maximum number of processes per day reached for user: {}", userId);
```
Comment (saalistaja) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/OnboardingServiceImpl.java:146]: Maybe we can include also the violated `maxProcessCountPerDay` value in the log message?

File: enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/database/OnboardingOtpRepository.java [hunk 4]
```diff
@@ -41,12 +41,13 @@ public interface OnboardingOtpRepository extends CrudRepository<OnboardingOtpEnt
     Optional<OnboardingOtpEntity> findLastOtp(String processId, OtpType type);
 
     @Modifying
-    @Query("UPDATE OnboardingOtpEntity o SET o.status = com.wultra.app.enrollmentserver.model.enumeration.OtpStatus.FAILED, " +
+    @Query("UPDATE OnboardingOtpEntity o SET " +
+            "o.status = com.wultra.app.enrollmentserver.model.enumeration.OtpStatus.FAILED, " +
             "o.timestampLastUpdated = CURRENT_TIMESTAMP, " +
             "o.errorDetail = 'expired' " +
```
Comment (saalistaja) [inline enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/database/OnboardingOtpRepository.java:47]: Could we use a constant here for the `defined` text? It seems to be same at several other places.

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/OnboardingServiceImpl.java [hunk 5]
```diff
@@ -139,6 +133,20 @@ public OnboardingStartResponse startOnboarding(OnboardingStartRequest request) t
             process.setTimestampCreated(new Date());
         }
         process = onboardingProcessRepository.save(process);
+
+        // Check for brute force attacks
+        Calendar c = GregorianCalendar.getInstance();
```
Comment (saalistaja) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/OnboardingServiceImpl.java:138]: The one day window is a little bit hardcoded. Could we define it dynamically in similar way as other durations?

E.g. two config props
```
int maxProcessCountPerPeriod
Duration maxProcessCountPeriod
```
and have
```
...
Date timestampCheckStart = DateUtil.convertExpirationToCreatedDate(maxProcessCountPeriod)
...
```

**Review by saalistaja — APPROVED** [review]
Looks really good. I have mentioned only few minor tips mentioned.

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/configuration/IdentityVerificationConfig.java (hunk 2 above)
Comment (romanstrobl) [reply enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/configuration/IdentityVerificationConfig.java]: I think `5m` is too little. The user may need more than 5 minutes to get the ID card and driver's license.

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/OnboardingServiceImpl.java (hunk 5 above)
Comment (romanstrobl) [reply enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/OnboardingServiceImpl.java:138]: There was no such request for customized timeframe period checks from the client. But we can surely implement this as a separate enhancement. Feel free to raise an issue if you feel strongly about this.

File: enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/database/OnboardingOtpRepository.java (hunk 4 above)
Comment (romanstrobl) [reply enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/database/OnboardingOtpRepository.java:47]: Yes, we can use the constant, good point.

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/OnboardingServiceImpl.java (hunk 3 above)
Comment (romanstrobl) [reply enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/OnboardingServiceImpl.java:146]: Yes, I will add it.

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/configuration/IdentityVerificationConfig.java [hunk 6]
```diff
@@ -51,16 +53,22 @@ public class IdentityVerificationConfig {
     @Value("${enrollment-server-onboarding.presence-check.cleanupEnabled:false}")
     private boolean presenceCheckCleanupEnabled;
 
-    @Value("${enrollment-server-onboarding.identity-verification.data-retention.hours:1}")
-    private int dataRetentionTime;
+    @Value("${enrollment-server-onboarding.identity-verification.data-retention.hours:1h}")
```
Comment (banterCZ) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/configuration/IdentityVerificationConfig.java:56]: Since it is already type of `Duration`, I guess that _hours_ may be omit from property key.

File: enrollment-server-onboarding/src/main/resources/application.properties [hunk 7]
```diff
@@ -72,19 +72,20 @@ powerauth.service.security.clientSecret=
...
+enrollment-server-onboarding.onboarding-process.expiration=3h
+enrollment-server-onboarding.onboarding-process.activation.expiration=5m
+enrollment-server-onboarding.onboarding-process.verification.expiration=1h
 enrollment-server-onboarding.onboarding-process.max-processes-per-day=5
 
 # Identity Verification Configuration
 enrollment-server-onboarding.identity-verification.enabled=false
-enrollment-server-onboarding.identity-verification.data-retention.hours=1
-enrollment-server-onboarding.identity-verification.expiration.seconds=300
+enrollment-server-onboarding.identity-verification.data-retention=1h
```
Comment (banterCZ) [inline enrollment-server-onboarding/src/main/resources/application.properties:85]: Here, it is correctly without _hours_ This works only due to default value https://github.com/wultra/enrollment-server/pull/266/files#r923018751 I will fix it in a separate PR.

Comment (banterCZ) [reply enrollment-server-onboarding/src/main/resources/application.properties:85]: https://github.com/wultra/enrollment-server/pull/279

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/configuration/IdentityVerificationConfig.java (hunk 6 above)
Comment (romanstrobl) [reply enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/configuration/IdentityVerificationConfig.java:56]: Right, I was about to change this, but forgot about this place.
