### PR TITLE
Fix #1404: Process consent endpoints in transaction

### LINKED ISSUE #1404: Get consent text endpoint returns 500
### Affected product(s) and version(s)

_No response_

### Environment

DEV

### Steps to reproduce, current result, expected result

_No response_

### Log output

_No response_

### PR DESCRIPTION
**Pull request by michal-rozehnal-w**

### CODE REVIEW

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationRestService.java [hunk 1]
```diff
@@ -504,6 +504,7 @@ public Response cleanup(ObjectRequest<IdentityVerificationCleanupRequest> reques
      * @throws OnboardingProcessException Thrown when onboarding process is not found.
      * @throws PowerAuthEncryptionException Thrown when request decryption fails.
      */
+    @Transactional
```
Comment (michal-rozehnal-w) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationRestService.java:507]: It causes problem [here](https://github.com/wultra/enrollment-server/blob/develop/enrollment-server-onboard[…]ra/app/onboardingserver/impl/service/OnboardingServiceImpl.java). The `process.getProcessConfiguration()` is lazy evaluation and outside of transaction it throws `LazyInitializationException`. Alternative way is to use eager loading

**Review by banterCZ — APPROVED** [review]
Thanks for the fix!
