### PR TITLE
Fix #478: InvalidRequestObjectException handler

### LINKED ISSUE #478: InvalidRequestObjectException hadler
Texting is confusing, speaking about push server and mobile token.

### PR DESCRIPTION
**Pull request by banterCZ**

### CODE REVIEW

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/errorhandling/DefaultExceptionHandler.java [hunk 1]
```diff
@@ -63,8 +63,8 @@ public class DefaultExceptionHandler {
     @ExceptionHandler(InvalidRequestObjectException.class)
     @ResponseStatus(HttpStatus.BAD_REQUEST)
     public @ResponseBody ErrorResponse handleInvalidRequestException(InvalidRequestObjectException ex) {
-        logger.warn("Error occurred when registering to push server.", ex);
-        return new ErrorResponse("INVALID_REQUEST", "Invalid request object sent to Mobile Token API component.");
+        logger.warn("Error occurred when processing request object.", ex);
```
Comment (banterCZ) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/errorhandling/DefaultExceptionHandler.java:66]: Texting is confusing. The exception is related not only to push server or mtoken. It is thrown in `ActivationCodeService`, `PushRegistrationService` and `OnboardingServiceImpl`.

**Review by romanstrobl — APPROVED** [review]
Good catch!
