### PR TITLE
Fix #302: SCA verification step must not leak information

### LINKED ISSUE #302: SCA verification step must not leak information about individual factor failures
In case face verification fails, go to the OTP verification step and inform user about error after OTP verification. The user should not be able to differentiate the reason for failure.

### PR DESCRIPTION
**Pull request by banterCZ**

### CODE REVIEW

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationOtpService.java [hunk 1]
```diff
@@ -133,6 +155,54 @@ public boolean isUserVerifiedUsingOtp(String processId) {
...
+        }
+
+        logger.debug("Evaluating result of presence check, Process ID: {}", processId);
+
+        final IdentityVerificationEntity idVerification = identityVerificationRepository.findFirstByActivationIdOrderByTimestampCreatedDesc(process.getActivationId()).orElseThrow(() ->
+                new OnboardingProcessException("No IdentityVerification found for Process ID: " + processId));
+        final String errorDetail = idVerification.getErrorDetail();
+        final String rejectReason = idVerification.getRejectReason();
+
+        if (StringUtils.isNotBlank(errorDetail) || StringUtils.isNotBlank(rejectReason)) {
```
Comment (banterCZ) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationOtpService.java:172]: Is it save enough to base detection of _presence check_ just on missing error detail and reject reason or to add another db column?

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationOtpService.java [hunk 2]
```diff
@@ -133,6 +155,54 @@ public boolean isUserVerifiedUsingOtp(String processId) {
...
+            logger.debug("PRESENCE_CHECK without error or reject reason, Process ID: {}", idVerification.getProcessId());
+        }
+        return response;
+    }
+
+    private void markVerificationOtpAsFailed(String processId) throws OnboardingProcessException {
+        final OnboardingOtpEntity otp = onboardingOtpRepository.findLastOtp(processId, OtpType.USER_VERIFICATION).orElseThrow(() ->
+            new OnboardingProcessException("Onboarding OTP not found for process ID: " + processId));
+        otp.setStatus(OtpStatus.FAILED);
+        otp.setErrorDetail(OnboardingOtpEntity.ERROR_CANCELED);
```
Comment (banterCZ) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationOtpService.java:201]: Mark otp as failed just to be sure not to re-use it. The question is whether to introduce a new error detail.

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationOtpService.java [hunk 3]
```diff
@@ -141,10 +211,6 @@ public boolean isUserVerifiedUsingOtp(String processId) {
      * @throws OnboardingOtpDeliveryException Thrown when OTP code could not be sent.
      */
     private void sendOtpCode(String processId, boolean isResend) throws OnboardingProcessException, OnboardingOtpDeliveryException {
-        if (onboardingProvider == null) {
```
Comment (banterCZ) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationOtpService.java:144]: Already NPE safe because of autoconfiguration.

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationOtpService.java [hunk 4]
```diff
@@ -110,13 +132,13 @@ public void sendOtp(OwnerId ownerId, IdentityVerificationEntity identityVerifica
      * @throws OnboardingProcessException Thrown when onboarding process is not found.
      */
     public OtpVerifyResponse verifyOtpCode(String processId, String otpCode) throws OnboardingProcessException {
```
Comment (banterCZ) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationOtpService.java:134]: Does it make sense to include `remainingAttempts` in the response from SCA point of view?

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationStatusService.java [hunk 5]
```diff
@@ -168,19 +172,18 @@ public IdentityVerificationStatusResponse checkIdentityVerificationStatus(Identi
...
                     idVerification.setTimestampLastUpdated(ownerId.getTimestamp());
                 }
 
                 if (presenceCheckResult != null) {
                     evaluatePresenceCheckResult(ownerId, idVerification, presenceCheckResult);
                 }
             }
-        } else if (IdentityVerificationPhase.PRESENCE_CHECK.equals(idVerification.getPhase())
-                && IdentityVerificationStatus.VERIFICATION_PENDING.equals(idVerification.getStatus())) {
+        } else if (isPresenceCheckFinished(idVerification.getPhase(), idVerification.getStatus())) {
```
Comment (banterCZ) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationStatusService.java:183]: The main change in _status service_, now FAILED and REJECTED are accepted to pass to the next step because of SCA.

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationOtpService.java [hunk 6]
```diff
@@ -133,6 +164,66 @@ public boolean isUserVerifiedUsingOtp(String processId) {
...
+        }
+        return response;
+    }
+
+    private IdentityVerificationEntity getIdentityVerificationEntity(final OnboardingProcessEntity process) throws OnboardingProcessException {
+        return identityVerificationRepository.findFirstByActivationIdOrderByTimestampCreatedDesc(process.getActivationId()).orElseThrow(() ->
+                new OnboardingProcessException("No IdentityVerification found for Process ID: " + process.getId()));
+    }
+
+    private OtpVerifyResponse moveToPhasePresenceCheck(
```
Comment (banterCZ) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationOtpService.java:195]: Hopefully, it will be refactored later on, when it is rewritten to the state machine. I guess to publish an event or so.

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationOtpService.java (hunk 2 above)
Comment (saalistaja) [reply enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationOtpService.java:222]: `Onboarding OTP not found, Process ID: ` ?

**Review by saalistaja — APPROVED** [review]
Looks good.

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationOtpService.java (hunk 1 above)
Comment (romanstrobl) [reply enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationOtpService.java:180]: It should work for now. We can improve this functionality in a future pull request.

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationOtpService.java (hunk 4 above)
Comment (romanstrobl) [reply enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationOtpService.java:138]: Yes, this information is useful for the mobile application.

**Review by romanstrobl — APPROVED** [review]
We may have to improve the detection of failed presence check in the future, but let's merge this pull request, it is an improvement.
