### PR TITLE
Fix #1166: Duplicate package in component scan

### LINKED ISSUE #1166: Duplicate package in component scan
Duplicate packages after refactoring:

```
@ComponentScan(basePackages = {
        "com.wultra.security.powerauth",
        "com.wultra.security.powerauth",
})
```

### Affected product(s) and version(s)

_No response_

### Environment

_No response_

### Steps to reproduce, current result, expected result

Incorrect package names after refactoring:

### Log output

_No response_

### PR DESCRIPTION
**Pull request by romanstrobl**

### CODE REVIEW

**Review by zcgandcomp — APPROVED** [review]
Looks OK.

File: enrollment-server/src/main/java/com/wultra/app/enrollmentserver/configuration/PowerAuthWebServiceConfiguration.java [hunk 1]
```diff
@@ -41,8 +41,7 @@
 @Configuration
 @ConfigurationProperties("ext")
 @ComponentScan(basePackages = {
-        "com.wultra.security.powerauth",
-        "io.getlime.security.powerauth",
+        "com.wultra.security.powerauth"
```
Comment (banterCZ) [inline enrollment-server/src/main/java/com/wultra/app/enrollmentserver/configuration/PowerAuthWebServiceConfiguration.java]: Nitpick: It may be simplified even into `@ComponentScan("com.wultra.security.powerauth")`

**Review by banterCZ — APPROVED** [review]
As expected.

File: enrollment-server/src/main/java/com/wultra/app/enrollmentserver/configuration/PowerAuthWebServiceConfiguration.java (hunk 1 above)
Comment (banterCZ) [reply enrollment-server/src/main/java/com/wultra/app/enrollmentserver/configuration/PowerAuthWebServiceConfiguration.java]: It is not crucial (just „figure skating“ 😉), but the point was that `value` is an alias for `basePackages`, so it is not needed at all.
```java
@AliasFor("value")
String[] basePackages() default {};
```

**Review by banterCZ — APPROVED** [review]

File: enrollment-server/src/main/java/com/wultra/app/enrollmentserver/configuration/PowerAuthWebServiceConfiguration.java (hunk 1 above)
Comment (romanstrobl) [reply enrollment-server/src/main/java/com/wultra/app/enrollmentserver/configuration/PowerAuthWebServiceConfiguration.java]: Ah, ok, sure.

**Review by banterCZ — APPROVED** [review]
Nice, thanks!
