### PR TITLE
Fix #1752: [release/2.0.x] Remove duplicated es_document_data index

### LINKED ISSUE #1752: Fix Liquibase migration to 2.1
### Affected product(s) and version(s)

_No response_

### Environment

_No response_

### Steps to reproduce, current result, expected result

Index on `es_document_data.timestamp_created` already exists bud it is created in the migration script to version 2.1, just with different name. Remove creation of duplicated index

### Log output

so-1      | ERROR: Exception Details
eso-1      | [2026-04-29 13:20:26] INFO [liquibase.ui] ERROR: Exception Details
eso-1      | ERROR: Exception Primary Class:  OracleDatabaseException
eso-1      | [2026-04-29 13:20:26] INFO [liquibase.ui] ERROR: Exception Primary Class:  OracleDatabaseException
eso-1      | ERROR: Exception Primary Reason:  ORA-01408: such column list already indexed
eso-1      |
eso-1      | [2026-04-29 13:20:26] INFO [liquibase.ui] ERROR: Exception Primary Reason:  ORA-01408: such column list already indexed
eso-1      |
eso-1      | ERROR: Exception Primary Source:  Oracle Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
eso-1      | Version 19.3.0.0.0
eso-1      | [2026-04-29 13:20:26] INFO [liquibase.ui] ERROR: Exception Primary Source:  Oracle Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
eso-1      | Version 19.3.0.0.0
eso-1      | [2026-04-29 13:20:26] INFO [liquibase.command] Command execution complete
eso-1      | [2026-04-29 13:20:26] SEVERE [liquibase.integration] Migration failed for changeset enrollment-server-onboarding/2.0.x/20260116-add-processed-document-data-table.xml::6::Michal Rozehnal:
eso-1      |      Reason: liquibase.exception.DatabaseException: ORA-01408: such column list already indexed
eso-1      |  [Failed SQL: (1408) CREATE INDEX POWERAUTH.es_document_data_timestamp_created_idx ON POWERAUTH.es_document_data(timestamp_created)]
eso-1      | liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset enrollment-server-onboarding/2.0.x/20260116-add-processed-document-data-table.xml::6::Michal Rozehnal:
eso-1      |      Reason: liquibase.exception.DatabaseException: ORA-01408: such column list already indexed
eso-1      |  [Failed SQL: (1408) CREATE INDEX POWERAUTH.es_document_data_timestamp_created_idx ON POWERAUTH.es_document_data(timestamp_created)]
eso-1      |    at liquibase.command.CommandScope.lambda$execute$6(CommandScope.java:310)
eso-1      |    at liquibase.Scope.child(Scope.java:225)
eso-1      |    at liquibase.Scope.child(Scope.java:201)

### PR DESCRIPTION
**Pull request by michal-rozehnal-w**
(cherrypick of https://github.com/wultra/enrollment-server/commit/8c26443569afb475a2cdc244eb9e23555d282748)

### CODE REVIEW

File: docs/sql/oracle/onboarding/create-schema.sql [hunk 1]
```diff
@@ -263,10 +263,34 @@ ALTER TABLE es_onboarding_process ADD process_config_id NUMBER(38, 0);
 
 ALTER TABLE es_onboarding_process ADD CONSTRAINT es_onboarding_process_process_config_id_fk FOREIGN KEY (process_config_id) REFERENCES es_onboarding_process_configuration (id);
 
--- Changeset enrollment-server-onboarding/2.1.x/20251219-process-target-activation-id.xml::1::Lubos Racansky
+-- Changeset enrollment-server-onboarding/2.0.x/20251219-process-target-activation-id.xml::1::Lubos Racansky
 -- Create a new column target_activation_id to es_onboarding_process
 ALTER TABLE es_onboarding_process ADD target_activation_id VARCHAR2(36);
 
+-- Changeset enrollment-server-onboarding/2.0.x/20260116-add-processed-document-data-table.xml::1::Michal Rozehnal
```
Comment (michal-rozehnal-w) [inline docs/sql/oracle/onboarding/create-schema.sql:270]: It seems that the changeset was missing from the SQL scripts for version `2.0.x`.

**Review by banterCZ — APPROVED** [review]
