### PR TITLE
Fix #1373: Generate verification id for documents result

### LINKED ISSUE #1373: Uploaded documents are stuck in CLIENT_EVALUATION
### Affected product(s) and version(s)

_No response_

### Environment

_No response_

### Steps to reproduce, current result, expected result

_No response_

### Log output

_No response_

### PR DESCRIPTION
**Pull request by michal-rozehnal-w**

### CODE REVIEW

File: enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java [hunk 1]
```diff
@@ -204,6 +210,7 @@ public DocumentsVerificationResult verifyDocuments(OwnerId ownerId, List<String>
                 .allMatch("Pass"::equalsIgnoreCase);
 
         final var result = new DocumentsVerificationResult();
+        result.setVerificationId(verificationId);
```
Comment (michal-rozehnal-w) [inline enrollment-server-onboarding-provider-microblink/src/main/java/com/wultra/app/onboardingserver/provider/microblink/MicroblinkDocumentVerificationProvider.java:213]: If this field is not set, then exception is thrown in [ClientEvaluationService](https://github.com/wultra/enrollment-server/blob/develop/enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/ClientEvaluationService.java#L106) and documentation verification process is stuck in `CLIENT_EVALUATION` phase

**Review by banterCZ — APPROVED** [review]
Looks good.
