### PR TITLE
Fix #348: Expired processes are not handled correctly

### LINKED ISSUE #348: Expired processes are not handled correctly
When an onboarding process expires during identity verification, the process status is changed on the backend, however the status is not checked during identity verification, hence the process continues. We should handle this properly by failing the identity verification. Documents should be failed as well. Identity verification and document fails should be done in cascade in one transaction together with failing the process. Orphan documents and identity verifications should fail as well in a separate job. We should log at least count of changes and be open to journal particular ids.

### PR DESCRIPTION
**Pull request by banterCZ**
Cleaning is done in cascade. Scheduling has been extracted from the service layer.

### CODE REVIEW

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationStatusService.java [hunk 1]
```diff
@@ -98,8 +98,6 @@ public IdentityVerificationStatusResponse checkIdentityVerificationStatus(Identi
 
         // Check for expiration of onboarding process
         if (onboardingService.hasProcessExpired(onboardingProcess)) {
-            // Trigger immediate processing of expired processes
-            onboardingService.terminateInactiveProcesses();
```
Comment (banterCZ) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/IdentityVerificationStatusService.java:102]: Let's keep the cleaning for the job only.

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/OnboardingServiceImpl.java [hunk 2]
```diff
@@ -202,8 +217,6 @@ public OnboardingStatusResponse getStatus(OnboardingStatusRequest request) throw
 
         // Check for expiration of onboarding process
         if (hasProcessExpired(process)) {
-            // Trigger immediate processing of expired processes
-            terminateInactiveProcesses();
```
Comment (banterCZ) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/OnboardingServiceImpl.java:206]: dtto

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/task/cleaning/CleaningService.java [hunk 3]
```diff
@@ -0,0 +1,203 @@
...
+import java.util.List;
+
+/**
+ * Service with cleaning functionality.
+ *
+ * @author Lubos Racansky, lubos.racansky@wultra.com
+ */
+@Service
+@Slf4j
+class CleaningService {
```
Comment (banterCZ) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/task/cleaning/CleaningService.java:49]: _package private_ on purpose. Classes are grouped by functionality, not by layers. This is not needed to expose out of job (so far).

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/task/cleaning/CleaningService.java [hunk 4]
```diff
@@ -0,0 +1,214 @@
...
+        final Date now = new Date();
+        final ErrorOrigin errorOrigin = ErrorOrigin.PROCESS_LIMIT_CHECK;
+
+        for (List<String> processIdChunk : Lists.partition(processIds, BATCH_SIZE)) {
+            logger.info("Terminating {} processes", processIdChunk.size());
+            onboardingProcessRepository.terminate(processIdChunk, now, errorDetail, errorOrigin);
+
+            final List<String> identityVerificationIds = identityVerificationRepository.findNotCompletedIdentityVerificationsByProcessIds(processIdChunk);
+            logger.info("Terminating {} identity verifications", identityVerificationIds.size());
+            identityVerificationRepository.terminate(identityVerificationIds, now, errorDetail, errorOrigin);
```
Comment (banterCZ) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/task/cleaning/CleaningService.java:207]: An attempt to do CQRS and be ready for auditing.

File: enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/database/DocumentVerificationRepository.java [hunk 5]
```diff
@@ -47,16 +48,10 @@ public interface DocumentVerificationRepository extends JpaRepository<DocumentVe
...
-    @Modifying
-    @Query("UPDATE DocumentVerificationEntity d " +
-            "SET d.status = com.wultra.app.enrollmentserver.model.enumeration.DocumentStatus.FAILED, " +
-            "    d.usedForVerification = false, " +
-            "    d.errorDetail = :errorMessage, " +
-            "    d.errorOrigin = :errorOrigin, " +
-            "    d.timestampLastUpdated = :timestamp " +
+    @Query("SELECT d.id FROM DocumentVerificationEntity d " +
             "WHERE d.timestampLastUpdated < :cleanupDate " +
             "AND d.status IN (:statuses)")
```
Comment (romanstrobl) [inline enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/database/DocumentVerificationRepository.java:53]: Are the brackets required in `(:statuses)`?

File: enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/database/DocumentVerificationRepository.java [hunk 6]
```diff
@@ -93,4 +88,32 @@ public interface DocumentVerificationRepository extends JpaRepository<DocumentVe
...
+     * Return document verification IDs by the given identity verification ID and document statuses.
+     *
+     * @param identityVerificationIds identity verification IDs
+     * @param statuses document statuses
+     * @return identity verification IDs
+     */
+    @Query("SELECT d.id FROM DocumentVerificationEntity d " +
+            "WHERE d.identityVerification.id in :identityVerificationIds " +
+            "AND d.status in :statuses")
+    List<String> findDocumentVerificationsByIdentityVerificationIdsAndStatuses(Collection<String> identityVerificationIds, Collection<DocumentStatus> statuses);
```
Comment (romanstrobl) [inline enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/database/DocumentVerificationRepository.java:101]: The method name is a bit confusing, because it uses naming which looks like Spring repository naming, however a `@Query` is specified. Using a shorter method name and not using `by` will resolve the issue.

File: enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/database/DocumentVerificationRepository.java [hunk 7]
```diff
@@ -47,16 +48,10 @@ public interface DocumentVerificationRepository extends JpaRepository<DocumentVe
...
-            "SET d.status = com.wultra.app.enrollmentserver.model.enumeration.DocumentStatus.FAILED, " +
-            "    d.usedForVerification = false, " +
-            "    d.errorDetail = :errorMessage, " +
-            "    d.errorOrigin = :errorOrigin, " +
-            "    d.timestampLastUpdated = :timestamp " +
+    @Query("SELECT d.id FROM DocumentVerificationEntity d " +
             "WHERE d.timestampLastUpdated < :cleanupDate " +
             "AND d.status IN (:statuses)")
-    int failExpiredVerifications(Date cleanupDate, Date timestamp, String errorMessage, ErrorOrigin errorOrigin, List<DocumentStatus> statuses);
+    List<String> findExpiredVerifications(Date cleanupDate, List<DocumentStatus> statuses);
```
Comment (romanstrobl) [inline enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/database/DocumentVerificationRepository.java:54]: What happens in case the query returns a lot of results? Will everything else work properly?

File: enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/database/IdentityVerificationRepository.java [hunk 8]
```diff
@@ -89,4 +91,46 @@ public interface IdentityVerificationRepository extends CrudRepository<IdentityV
...
+    /**
+     * Return identity verification IDs by the given process ID. Include only not yet finished entities.
+     *
+     * @param processIds process IDs
+     * @return identity verification IDs
+     */
+    @Query("SELECT i.id FROM IdentityVerificationEntity i " +
+            "WHERE i.processId in :processIds " +
+            "AND i.phase <> com.wultra.app.enrollmentserver.model.enumeration.IdentityVerificationPhase.COMPLETED")
+    List<String> findNotCompletedIdentityVerificationsByProcessIds(Collection<String> processIds);
```
Comment (romanstrobl) [inline enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/database/IdentityVerificationRepository.java:105]: dtto

File: enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/database/IdentityVerificationRepository.java [hunk 9]
```diff
@@ -89,4 +91,46 @@ public interface IdentityVerificationRepository extends CrudRepository<IdentityV
...
+     */
+    @Modifying
+    @Query("UPDATE IdentityVerificationEntity i SET " +
+            "i.phase = com.wultra.app.enrollmentserver.model.enumeration.IdentityVerificationPhase.COMPLETED, " +
+            "i.status = com.wultra.app.enrollmentserver.model.enumeration.OnboardingStatus.FAILED, " +
+            "i.timestampLastUpdated = :timestampExpired, " +
+            "i.timestampFailed = :timestampExpired, " +
+            "i.errorDetail = :errorDetail, " +
+            "i.errorOrigin = :errorOrigin " +
+            "WHERE i.id in :ids")
```
Comment (romanstrobl) [inline enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/database/IdentityVerificationRepository.java:134]: Let's capitalize `in`.

File: enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/database/OnboardingProcessRepository.java [hunk 10]
```diff
@@ -53,27 +55,45 @@ public interface OnboardingProcessRepository extends CrudRepository<OnboardingPr
...
             "p.status = com.wultra.app.enrollmentserver.model.enumeration.OnboardingStatus.FAILED, " +
             "p.timestampLastUpdated = :timestampExpired, " +
             "p.timestampFailed = :timestampExpired, " +
             "p.errorDetail = :errorDetail, " +
             "p.errorOrigin = :errorOrigin " +
-            "WHERE p.status <> com.wultra.app.enrollmentserver.model.enumeration.OnboardingStatus.FINISHED  " +
-            "AND p.status <> com.wultra.app.enrollmentserver.model.enumeration.OnboardingStatus.FAILED  " +
-            "AND p.timestampCreated < :dateCreatedBefore")
-    void terminateExpiredProcesses(Date dateCreatedBefore, Date timestampExpired, String errorDetail, ErrorOrigin errorOrigin);
+            "WHERE p.id in :ids")
```
Comment (romanstrobl) [inline enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/database/OnboardingProcessRepository.java:85]: Let's capitalize `in`.

File: enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/database/DocumentVerificationRepository.java (hunk 5 above)
Comment (banterCZ) [reply enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/database/DocumentVerificationRepository.java:53]: No, it works without them.

File: enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/database/DocumentVerificationRepository.java (hunk 7 above)
Comment (banterCZ) [reply enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/database/DocumentVerificationRepository.java:54]: Good catch, I will improve the scenario with many results.

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/task/cleaning/CleaningService.java [hunk 11]
```diff
@@ -0,0 +1,214 @@
...
+
+    /**
+     * Terminate expired document verifications.
+     */
+    @Transactional
+    public void terminateExpiredDocumentVerifications() {
+        final List<String> ids = documentVerificationRepository
+                .findExpiredVerifications(getVerificationExpirationTime(), DocumentStatus.ALL_NOT_FINISHED);
+        if (ids.isEmpty()) {
+            return;
```
Comment (romanstrobl) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/task/cleaning/CleaningService.java:157]: Add debug log message, please.

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/task/cleaning/CleaningService.java [hunk 12]
```diff
@@ -0,0 +1,214 @@
...
+    }
+
+    /**
+     * Terminate expired identity verifications.
+     */
+    @Transactional
+    public void terminateExpiredIdentityVerifications() {
+        final List<String> ids = identityVerificationRepository.findNotCompletedIdentityVerifications(getVerificationExpirationTime());
+        if (ids.isEmpty()) {
+            return;
```
Comment (romanstrobl) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/task/cleaning/CleaningService.java:174]: dtto

File: enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/task/cleaning/CleaningService.java [hunk 13]
```diff
@@ -0,0 +1,214 @@
...
+        return DateUtil.convertExpirationToCreatedDate(identityVerificationConfig.getDataRetentionTime());
+    }
+
+    private Date getVerificationExpirationTime() {
+        return DateUtil.convertExpirationToCreatedDate(identityVerificationConfig.getVerificationExpirationTime());
+    }
+
+    private void terminateProcessesAndRelatedEntities(final List<String> processIds, final String errorDetail) {
+        if (processIds.isEmpty()) {
+            return;
```
Comment (romanstrobl) [inline enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/task/cleaning/CleaningService.java:195]: dtto

File: enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/database/DocumentVerificationRepository.java (hunk 7 above)
Comment (banterCZ) [reply enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/database/DocumentVerificationRepository.java:54]: There is a hand break for Oracle because of limit at IN clause `for (List<String> idsChunk : Lists.partition(ids, BATCH_SIZE)) {` Theoretically, the transaction may expire, but the job runs quite often, so it should not handle thousands entries.
Let's postpone performance improvement, I will create a draft issue at least. Problem is, that JPQL doest not support LIMIT, native query is vendor specific and when using stream, we must process each entry separately, not in batch 😞

Comment (romanstrobl) [reply enrollment-server-onboarding-common/src/main/java/com/wultra/app/onboardingserver/common/database/DocumentVerificationRepository.java:54]: Agreed, under normal conditions, this should not be an issue. It will only happens once the app breaks down and then everything will just keep getting worse because the cleanup jobs will also not work. Anyway, this should not happen.
